// examples/consumers/vue-vite/src/pages/ModalConsumer.vue
<template>
  <main class="modal-consumer-page" data-testid="rozie-mount">
    <h2>ModalConsumer Demo</h2>
    <p>Dogfood: ModalConsumer.rozie composes Modal + WrapperModal with named, scoped, default, dynamic-name, and re-projected fills.</p>
    <ModalConsumerRozie :title="title" />
  </main>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import ModalConsumerRozie from '../../../../ModalConsumer.rozie';

const title = ref('Confirm action');
</script>

<style scoped>
.modal-consumer-page {
  padding: 1rem;
}
</style>

// examples/consumers/solid-vite/src/pages/ModalConsumer.tsx
import ModalConsumer from '../../../../ModalConsumer.rozie';

/**
 * Phase 07.2 Plan 06 — ModalConsumer dogfood page (Wave 2 close-out).
 *
 * ModalConsumer.rozie composes Modal + WrapperModal with named + scoped +
 * default-shorthand + dynamic-name + re-projected fills. The compiled Solid
 * output uses headerSlot/footerSlot props for named fills + `slots={{
 * [slotName()]: () => ... }}` for the dynamic-name fill (signal auto-call).
 */
export default function ModalConsumerPage() {
  return (
    <div data-testid="rozie-mount">
      <h2>ModalConsumer Demo</h2>
      <p>Dogfood: Modal + WrapperModal composed with named, scoped, default, dynamic-name, and re-projected fills.</p>
      <ModalConsumer title="Confirm action" />
    </div>
  );
}
