// examples/consumers/solid-vite/src/App.tsx
import { createSignal, createEffect, Show } from 'solid-js';
import CounterPage from './pages/CounterPage';
import SearchInputPage from './pages/SearchInputPage';
import DropdownPage from './pages/DropdownPage';
import TodoListPage from './pages/TodoListPage';
import ModalPage from './pages/ModalPage';
import CardPage from './pages/CardPage';
import CardHeaderPage from './pages/CardHeaderPage';
import TreeNodePage from './pages/TreeNodePage';
// Phase 07.2 Plan 06 — ModalConsumer dogfood page (Wave 2 close-out).
import ModalConsumerPage from './pages/ModalConsumer';
// Phase 16 — PropDefaultCoercion runtime probe (SPEC R1/R5 D-05 runtime arm).
import PropDefaultCoercionPage from './pages/PropDefaultCoercionPage';

/**
 * Page-routing shell for the Solid Vite demo.
 *
 * Uses hash-based routing (no @solidjs/router dependency) to keep the demo
 * minimal. Each Playwright e2e test navigates by changing the hash directly.
 *
 * Phase 06.3 P3 anchor: this is the consumer-facing surface that proves Phase
 * 06.3 end-to-end. All 8 reference .rozie examples render under Solid and
 * exercise the full @rozie/target-solid + @rozie/runtime-solid + @rozie/unplugin
 * chain.
 */
export function App() {
  const [route, setRoute] = createSignal(window.location.hash.slice(1) || '/counter');

  createEffect(() => {
    const handler = () => setRoute(window.location.hash.slice(1) || '/counter');
    window.addEventListener('hashchange', handler);
    return () => window.removeEventListener('hashchange', handler);
  });

  return (
    <div>
      <header
        style={{
          padding: '1rem',
          'border-bottom': '1px solid rgba(0, 0, 0, 0.08)',
          'font-family': 'system-ui, sans-serif',
        }}
      >
        <h1 style={{ margin: '0 0 0.5rem 0', 'font-size': '1.25rem' }}>
          Rozie Solid Demo
        </h1>
        <nav style={{ display: 'flex', gap: '0.25rem' }}>
          <a href="#/counter" data-testid="nav-counter">Counter</a>
          {' | '}
          <a href="#/search-input" data-testid="nav-search-input">SearchInput</a>
          {' | '}
          <a href="#/dropdown" data-testid="nav-dropdown">Dropdown</a>
          {' | '}
          <a href="#/todolist" data-testid="nav-todolist">TodoList</a>
          {' | '}
          <a href="#/modal" data-testid="nav-modal">Modal</a>
          {' | '}
          <a href="#/card" data-testid="nav-card">Card</a>
          {' | '}
          <a href="#/card-header" data-testid="nav-card-header">CardHeader</a>
          {' | '}
          <a href="#/treenode" data-testid="nav-treenode">TreeNode</a>
          {' | '}
          <a href="#/modal-consumer" data-testid="nav-modal-consumer">ModalConsumer</a>
          {' | '}
          <a href="#/prop-default-coercion" data-testid="nav-prop-default-coercion">PropDefaultCoercion</a>
        </nav>
      </header>
      <main style={{ padding: '1rem', 'font-family': 'system-ui, sans-serif' }}>
        <Show when={route() === '/counter'}><CounterPage /></Show>
        <Show when={route() === '/search-input'}><SearchInputPage /></Show>
        <Show when={route() === '/dropdown'}><DropdownPage /></Show>
        <Show when={route() === '/todolist'}><TodoListPage /></Show>
        <Show when={route() === '/modal'}><ModalPage /></Show>
        <Show when={route() === '/card'}><CardPage /></Show>
        <Show when={route() === '/card-header'}><CardHeaderPage /></Show>
        <Show when={route() === '/treenode'}><TreeNodePage /></Show>
        <Show when={route() === '/modal-consumer'}><ModalConsumerPage /></Show>
        <Show when={route() === '/prop-default-coercion'}><PropDefaultCoercionPage /></Show>
      </main>
    </div>
  );
}

// examples/consumers/react-vite/src/App.tsx
import { useState } from 'react';
import type { JSX } from 'react';
import CounterPage from './pages/CounterPage';
import SearchInputPage from './pages/SearchInputPage';
import DropdownPage from './pages/DropdownPage';
import TodoListPage from './pages/TodoListPage';
import ModalPage from './pages/ModalPage';
import TreeNodePage from './pages/TreeNodePage';
import CardPage from './pages/CardPage';
import CardHeaderPage from './pages/CardHeaderPage';
// Phase 07.2 Plan 06 — ModalConsumer dogfood page (Wave 2 close-out).
import ModalConsumerPage from './pages/ModalConsumerPage';
import LitInteropPage from './pages/LitInteropPage';
// Phase 16 — PropDefaultCoercion runtime probe (SPEC R1/R5 D-05 runtime arm).
import PropDefaultCoercionPage from './pages/PropDefaultCoercionPage';

/**
 * Page-routing shell. Each Playwright e2e test navigates by clicking
 * `data-testid="nav-<page>"` to reach the page under test. Counter is the
 * default landing page (matches the Vue demo convention).
 *
 * Plan 04-06 anchor: this is the consumer-facing surface that proves Phase 4
 * end-to-end. All 5 reference .rozie examples render under React StrictMode
 * (wrapped at main.tsx) and exercise the full @rozie/target-react +
 * @rozie/runtime-react + @rozie/unplugin chain.
 */
type PageKey =
  | 'counter'
  | 'search-input'
  | 'dropdown'
  | 'todo-list'
  | 'modal'
  | 'tree-node'
  | 'card'
  | 'card-header'
  | 'modal-consumer'
  | 'lit-interop'
  | 'prop-default-coercion';

const PAGES: Record<PageKey, () => JSX.Element> = {
  counter: CounterPage,
  'search-input': SearchInputPage,
  dropdown: DropdownPage,
  'todo-list': TodoListPage,
  modal: ModalPage,
  'tree-node': TreeNodePage,
  card: CardPage,
  'card-header': CardHeaderPage,
  'modal-consumer': ModalConsumerPage,
  'lit-interop': LitInteropPage,
  'prop-default-coercion': PropDefaultCoercionPage,
};

const PAGE_KEYS: ReadonlyArray<PageKey> = [
  'counter',
  'search-input',
  'dropdown',
  'todo-list',
  'modal',
  'tree-node',
  'card',
  'card-header',
  'modal-consumer',
  'lit-interop',
  'prop-default-coercion',
];

export default function App(): JSX.Element {
  const [current, setCurrent] = useState<PageKey>('counter');
  const PageComponent = PAGES[current];

  return (
    <>
      <header
        style={{
          padding: '1rem',
          borderBottom: '1px solid rgba(0, 0, 0, 0.08)',
          fontFamily: 'system-ui, sans-serif',
        }}
      >
        <h1 style={{ margin: '0 0 0.5rem 0', fontSize: '1.25rem' }}>
          Rozie React Demo
        </h1>
        <nav style={{ display: 'flex', gap: '0.25rem' }}>
          {PAGE_KEYS.map((p) => (
            <button
              key={p}
              data-testid={`nav-${p}`}
              onClick={() => setCurrent(p)}
              style={{
                padding: '0.25rem 0.5rem',
                font: 'inherit',
                border: '1px solid rgba(0, 0, 0, 0.15)',
                background: current === p ? 'rgba(0, 100, 200, 0.1)' : 'white',
                cursor: 'pointer',
                borderRadius: '4px',
              }}
            >
              {p}
            </button>
          ))}
        </nav>
      </header>
      <main
        data-testid="rozie-mount"
        style={{ padding: '1rem', fontFamily: 'system-ui, sans-serif' }}
      >
        <PageComponent />
      </main>
    </>
  );
}
