// examples/consumers/vue-vite/src/App.vue
<template>
  <header class="app-header">
    <h1>Rozie Vue Demo</h1>
    <nav>
      <button
        v-for="p in pages"
        :key="p"
        :data-testid="`nav-${p}`"
        :class="{ active: current === p }"
        @click="current = p"
      >
        {{ p }}
      </button>
    </nav>
  </header>
  <component :is="pageComponents[current]" />
</template>

<script setup lang="ts">
import { ref } from 'vue';
import Counter from './pages/Counter.vue';
import SearchInput from './pages/SearchInput.vue';
import Dropdown from './pages/Dropdown.vue';
import TodoList from './pages/TodoList.vue';
import Modal from './pages/Modal.vue';
import TreeNode from './pages/TreeNode.vue';
import Card from './pages/Card.vue';
import CardHeader from './pages/CardHeader.vue';
// Phase 07.2 Plan 06 — ModalConsumer dogfood page (Wave 2 close-out).
import ModalConsumer from './pages/ModalConsumer.vue';
// Phase 16 — PropDefaultCoercion runtime probe (SPEC R1/R5 D-05 runtime arm).
import PropDefaultCoercion from './pages/PropDefaultCoercion.vue';
import { litInteropRoute } from './router';

const pages = [
  'Counter',
  'SearchInput',
  'Dropdown',
  'TodoList',
  'Modal',
  'TreeNode',
  'Card',
  'CardHeader',
  'ModalConsumer',
  'PropDefaultCoercion',
  'lit-interop',
] as const;
type Page = typeof pages[number];

const pageComponents: Record<Page, unknown> = {
  Counter,
  SearchInput,
  Dropdown,
  TodoList,
  Modal,
  TreeNode,
  Card,
  CardHeader,
  ModalConsumer,
  PropDefaultCoercion,
  'lit-interop': litInteropRoute.component,
};

const current = ref<Page>('Counter');
</script>

<style scoped>
.app-header {
  padding: 1rem;
  border-bottom: 1px solid rgba(0, 0, 0, 0.08);
  font-family: system-ui, sans-serif;
}
.app-header h1 {
  margin: 0 0 0.5rem 0;
  font-size: 1.25rem;
}
nav {
  display: flex;
  gap: 0.25rem;
}
button {
  padding: 0.25rem 0.5rem;
  font: inherit;
  border: 1px solid rgba(0, 0, 0, 0.15);
  background: white;
  cursor: pointer;
  border-radius: 4px;
}
button.active {
  background: rgba(0, 100, 200, 0.1);
  border-color: rgba(0, 100, 200, 0.5);
}
</style>

// examples/consumers/react-vite/src/App.tsx
import { useState } from 'react';
import type { JSX } from 'react';
import CounterPage from './pages/CounterPage';
import SearchInputPage from './pages/SearchInputPage';
import DropdownPage from './pages/DropdownPage';
import TodoListPage from './pages/TodoListPage';
import ModalPage from './pages/ModalPage';
import TreeNodePage from './pages/TreeNodePage';
import CardPage from './pages/CardPage';
import CardHeaderPage from './pages/CardHeaderPage';
// Phase 07.2 Plan 06 — ModalConsumer dogfood page (Wave 2 close-out).
import ModalConsumerPage from './pages/ModalConsumerPage';
import LitInteropPage from './pages/LitInteropPage';
// Phase 16 — PropDefaultCoercion runtime probe (SPEC R1/R5 D-05 runtime arm).
import PropDefaultCoercionPage from './pages/PropDefaultCoercionPage';

/**
 * Page-routing shell. Each Playwright e2e test navigates by clicking
 * `data-testid="nav-<page>"` to reach the page under test. Counter is the
 * default landing page (matches the Vue demo convention).
 *
 * Plan 04-06 anchor: this is the consumer-facing surface that proves Phase 4
 * end-to-end. All 5 reference .rozie examples render under React StrictMode
 * (wrapped at main.tsx) and exercise the full @rozie/target-react +
 * @rozie/runtime-react + @rozie/unplugin chain.
 */
type PageKey =
  | 'counter'
  | 'search-input'
  | 'dropdown'
  | 'todo-list'
  | 'modal'
  | 'tree-node'
  | 'card'
  | 'card-header'
  | 'modal-consumer'
  | 'lit-interop'
  | 'prop-default-coercion';

const PAGES: Record<PageKey, () => JSX.Element> = {
  counter: CounterPage,
  'search-input': SearchInputPage,
  dropdown: DropdownPage,
  'todo-list': TodoListPage,
  modal: ModalPage,
  'tree-node': TreeNodePage,
  card: CardPage,
  'card-header': CardHeaderPage,
  'modal-consumer': ModalConsumerPage,
  'lit-interop': LitInteropPage,
  'prop-default-coercion': PropDefaultCoercionPage,
};

const PAGE_KEYS: ReadonlyArray<PageKey> = [
  'counter',
  'search-input',
  'dropdown',
  'todo-list',
  'modal',
  'tree-node',
  'card',
  'card-header',
  'modal-consumer',
  'lit-interop',
  'prop-default-coercion',
];

export default function App(): JSX.Element {
  const [current, setCurrent] = useState<PageKey>('counter');
  const PageComponent = PAGES[current];

  return (
    <>
      <header
        style={{
          padding: '1rem',
          borderBottom: '1px solid rgba(0, 0, 0, 0.08)',
          fontFamily: 'system-ui, sans-serif',
        }}
      >
        <h1 style={{ margin: '0 0 0.5rem 0', fontSize: '1.25rem' }}>
          Rozie React Demo
        </h1>
        <nav style={{ display: 'flex', gap: '0.25rem' }}>
          {PAGE_KEYS.map((p) => (
            <button
              key={p}
              data-testid={`nav-${p}`}
              onClick={() => setCurrent(p)}
              style={{
                padding: '0.25rem 0.5rem',
                font: 'inherit',
                border: '1px solid rgba(0, 0, 0, 0.15)',
                background: current === p ? 'rgba(0, 100, 200, 0.1)' : 'white',
                cursor: 'pointer',
                borderRadius: '4px',
              }}
            >
              {p}
            </button>
          ))}
        </nav>
      </header>
      <main
        data-testid="rozie-mount"
        style={{ padding: '1rem', fontFamily: 'system-ui, sans-serif' }}
      >
        <PageComponent />
      </main>
    </>
  );
}
