// examples/consumers/svelte-ts/fixtures/DynamicSlots.svelte
<script lang="ts">
import { applyListeners, rozieDisplay } from '@rozie/runtime-svelte';

import type { Snippet } from 'svelte';

interface Props {
  row?: any;
  total?: number;
  cellKey?: string;
  freeSlotName?: string;
  snippets?: { 'cell-total'?: Snippet<[{ value: any }]>; [key: `cell-${string}`]: Snippet<[{ row: any; value: any }]>; [key: `row-${string}`]: Snippet; } & Record<string, any>;
  [key: string]: unknown;
}

let __defaultRow = (() => ({}))();

let {
  row = __defaultRow,
  total = 0,
  cellKey = 'status',
  freeSlotName = 'freeform',
  snippets,
  ...__rozieAttrs
}: Props = $props();

const __rozieSlot_cellTotal = $derived(snippets?.['cell-total']);
const __rozieDynSlot1 = $derived(snippets?.[`cell-${cellKey}`]);
const __rozieDynSlot2 = $derived(snippets?.[`row-${freeSlotName}`]);
</script>

<div {...__rozieAttrs} class={["dynamic-slots", (__rozieAttrs)?.class]} use:applyListeners={__rozieAttrs} data-rozie-s-96693586>{#if __rozieSlot_cellTotal}{@render __rozieSlot_cellTotal({ value: total })}{:else}<strong data-rozie-s-96693586>{total}</strong>{/if}{#if __rozieDynSlot1}{@render __rozieDynSlot1({ row, value: row[cellKey] })}{:else}<span data-rozie-s-96693586>{rozieDisplay(row[cellKey])}</span>{/if}{#if __rozieDynSlot2}{@render __rozieDynSlot2()}{:else}<em data-rozie-s-96693586>fallback</em>{/if}</div>

// examples/consumers/solid-ts/fixtures/DynamicSlots.tsx
import type { JSX } from 'solid-js';
import { mergeProps, splitProps } from 'solid-js';
import { rozieDisplay } from '@rozie/runtime-solid';

interface DynamicSlotsProps {
  row?: Record<string, any>;
  total?: number;
  cellKey?: string;
  freeSlotName?: string;
  slots?: { 'cell-total'?: ((ctx: { value: any }) => JSX.Element) | undefined; [key: `cell-${string}`]: ((ctx: { row: any; value: any }) => JSX.Element) | undefined; [key: `row-${string}`]: (() => JSX.Element) | undefined; [key: string]: ((...args: any[]) => JSX.Element) | undefined; };
}

export default function DynamicSlots(_props: DynamicSlotsProps): JSX.Element {
  const _merged = mergeProps({ row: (() => ({}))() as Record<string, any>, total: 0, cellKey: 'status', freeSlotName: 'freeform' }, _props);
  const [local, attrs] = splitProps(_merged, ['row', 'total', 'cellKey', 'freeSlotName']);

  return (
    <>
    <div {...attrs} class={"dynamic-slots" + (((attrs as unknown as Record<string, unknown>).class as string | undefined) ? " " + ((attrs as unknown as Record<string, unknown>).class as string | undefined) : "")} data-rozie-s-96693586="">

      
      {_props.slots?.['cell-total']?.({ value: local.total }) ?? <strong data-rozie-s-96693586="">{local.total}</strong>}

      
      {_props.slots?.[`cell-${local.cellKey}`]?.({ row: local.row, value: local.row[local.cellKey] }) ?? <span data-rozie-s-96693586="">{rozieDisplay(local.row[local.cellKey])}</span>}

      
      {_props.slots?.[`row-${local.freeSlotName}`]?.() ?? <em data-rozie-s-96693586="">fallback</em>}

    </div>
    </>
  );
}
