// examples/consumers/vue-ts/fixtures/TypedEvents.vue
<template>

  <div class="typed-events" v-bind="$attrs">
    <button class="bump" @click="bump()">+</button>
    <button class="clear" @click="clear()" @dblclick="emit('select', count)">reset</button>
    <button class="open" @click="emit('row-open', { index: count })">open</button>
    <slot name="row" :count="count" :tone="props.tone"></slot>
  </div>

</template>

<script lang="ts">
export type Count = number;
export interface PingPayload {
  count: Count;
  label: string;
}

export interface TypedEventsHandle {
  bump: () => void;
  clear: (...args: any[]) => any;
  getCount: () => number;
  jump: (to: number) => void;
}
</script>

<script setup lang="ts">
import { ref } from 'vue';

const props = withDefaults(
  defineProps<{ tone?: string }>(),
  { tone: 'info' }
);

const emit = defineEmits<{
  ping: [payload: PingPayload];
  reset: [];
  select: [payload: number];
  'row-open': [payload: {
  index: number;
}];
}>();

defineSlots<{
  row(props: { count: Count; tone: string }): any;
}>();

const count = ref(0);

function bump() {
  const next = count.value + 1;
  count.value = next;
  emit('ping', {
    count: next,
    label: props.tone
  });
}
function clear() {
  count.value = 0;
  emit('reset');
}
function getCount() {
  return count.value;
}
function jump(...a: any[]) {
  count.value = a.length;
}

defineExpose({ bump, clear, getCount, jump } as TypedEventsHandle);
</script>

// examples/consumers/svelte-ts/fixtures/TypedEvents.svelte
<script module lang="ts">
export type Count = number;
export interface PingPayload {
  count: Count;
  label: string;
}
</script>
<script lang="ts">
import { applyListeners } from '@rozie/runtime-svelte';

import type { Snippet } from 'svelte';

interface Props extends Omit<import('svelte/elements').SvelteHTMLElements['div'], 'tone' | 'row' | 'snippets' | 'onping' | 'onreset' | 'onselect' | 'onrowopen' | 'index' | 'children'> {
  tone?: string;
  row?: Snippet<[{ count: Count; tone: string }]>;
  snippets?: Record<string, any>;
  onping?: (payload: PingPayload) => void;
  onreset?: () => void;
  onselect?: (payload: number) => void;
  onrowopen?: (payload: {
  index: number;
}) => void;
}

let {
  tone = 'info',
  row: __rowProp,
  snippets,
  onping,
  onreset,
  onselect,
  onrowopen,
  ...__rozieAttrs
}: Props = $props();

const row = $derived(__rowProp ?? snippets?.row);

let count = $state(0);

export function bump(): void;
export function bump() {
  const next = count + 1;
  count = next;
  onping?.({
    count: next,
    label: tone
  });
}
export function clear(...args: any[]): any;
export function clear() {
  count = 0;
  onreset?.();
}
export function getCount(): number;
export function getCount() {
  return count;
}
export function jump(to: number): void;
export function jump(...a: any[]) {
  count = a.length;
}
</script>

<div {...__rozieAttrs} class={["typed-events", (__rozieAttrs)?.class]} use:applyListeners={__rozieAttrs} data-rozie-s-78e83372><button class="bump" onclick={($event) => { bump(); }} data-rozie-s-78e83372>+</button><button class="clear" onclick={($event) => { clear(); }} ondblclick={($event) => { onselect?.(count); }} data-rozie-s-78e83372>reset</button><button class="open" onclick={($event) => { onrowopen?.({ index: count }); }} data-rozie-s-78e83372>open</button>{@render row?.({ count, tone })}</div>
