// packages/ui/tags/packages/angular/src/Tags.ts
import { Component, ContentChild, DestroyRef, ElementRef, Renderer2, TemplateRef, ViewEncapsulation, afterRenderEffect, computed, contentChildren, effect, forwardRef, inject, input, model, output, signal, viewChild } from '@angular/core';
import { NgClass, NgTemplateOutlet } from '@angular/common';
import { NG_VALUE_ACCESSOR } from '@angular/forms';
import { RozieSlot, createRozieAttrApplier, createRozieHostAttrsReader, rozieAttr as __rozieAttr, rozieDisplay as __rozieDisplay } from '@rozie/runtime-angular';

interface TagCtx {
  $implicit: { tag: any; index: any; remove: any };
  tag: any;
  index: any;
  remove: any;
}

@Component({
  selector: 'rozie-tags',
  standalone: true,
  imports: [NgTemplateOutlet, NgClass],
  template: `

    <div class="rozie-tags" [ngClass]="{ 'rozie-tags--disabled': (disabled() || this.__rozieCvaDisabled()), 'rozie-tags--readonly': readonly() }" #root role="group" [attr.aria-label]="rozieAttr(ariaLabel())" #rozieSpread_0 #rozieListenersTarget_1>
      <ul class="rozie-tags-list">
        @for (t of tokens(); track t + ':' + tokens().indexOf(t)) {
    <li class="rozie-tags-chip">
          @if ((tagTpl ?? __rozieFillMap()['tag'] ?? templates()?.['tag'])) {
    <ng-container *ngTemplateOutlet="(tagTpl ?? __rozieFillMap()['tag'] ?? templates()?.['tag']); context: _tag_ctx_2(t)" />
    } @else {

            <span class="rozie-tags-chip__label">{{ rozieDisplay(t) }}</span>
            @if (!readonly()) {
    <button type="button" class="rozie-tags-chip__remove" [disabled]="!!(disabled() || this.__rozieCvaDisabled())" [attr.aria-label]="rozieAttr(removeLabel(t))" (click)="removeAt(tokens().indexOf(t))">×</button>
    }
    }
        </li>
    }
      </ul>

      @if (!readonly()) {
    <input class="rozie-tags-input" type="text" autocomplete="off" autocapitalize="off" [value]="draft()" [placeholder]="placeholder()" [disabled]="!!(disabled() || this.__rozieCvaDisabled()) || !!atMax()" [attr.aria-label]="rozieAttr(ariaLabel())" [attr.aria-disabled]="!!(disabled() || this.__rozieCvaDisabled())" (input)="onInput($event)" (keydown)="onKeydown($event)" (paste)="onPaste($event)" (blur)="onBlur($event)" />
    }<span class="rozie-tags-count" aria-live="polite">{{ rozieDisplay(countLabel()) }}</span>
    </div>

  `,
  styles: [`
    :host(rozie-tags) { display: contents; }
    .rozie-tags {
      display: inline-flex;
      flex-wrap: wrap;
      align-items: center;
      gap: var(--rozie-tags-gap, var(--rtg-gap, 0.4rem));
      padding: var(--rozie-tags-padding, var(--rtg-padding, 0.35rem 0.45rem));
      font: var(--rozie-tags-font, inherit);
      background: var(--rozie-tags-bg, var(--rtg-bg, #fff));
      border: var(--rozie-tags-border-width, var(--rtg-border-width, 1px)) solid var(--rozie-tags-border-color, var(--rtg-border-color, rgba(0, 0, 0, 0.25)));
      border-radius: var(--rozie-tags-radius, var(--rtg-radius, 0.5rem));
      min-width: var(--rozie-tags-min-width, var(--rtg-min-width, 12rem));
    }
    .rozie-tags:focus-within {
      border-color: var(--rozie-tags-accent, var(--rtg-accent, #0066cc));
      box-shadow: 0 0 0 var(--rozie-tags-focus-ring-width, var(--rtg-focus-ring-width, 3px)) var(--rozie-tags-focus-ring-color, var(--rtg-focus-ring-color, rgba(0, 102, 204, 0.25)));
    }
    .rozie-tags-list {
      display: contents;
      margin: 0;
      padding: 0;
      list-style: none;
    }
    .rozie-tags-chip {
      display: inline-flex;
      align-items: center;
      gap: var(--rozie-tags-chip-gap, var(--rtg-chip-gap, 0.3rem));
      padding: var(--rozie-tags-chip-padding, var(--rtg-chip-padding, 0.15rem 0.5rem));
      font-size: var(--rozie-tags-chip-font-size, var(--rtg-chip-font-size, 0.85rem));
      color: var(--rozie-tags-chip-color, var(--rtg-chip-color, inherit));
      background: var(--rozie-tags-chip-bg, var(--rtg-chip-bg, rgba(0, 102, 204, 0.12)));
      border-radius: var(--rozie-tags-chip-radius, var(--rtg-chip-radius, 0.375rem));
      white-space: nowrap;
    }
    .rozie-tags-chip__remove {
      display: inline-flex;
      align-items: center;
      justify-content: center;
      width: var(--rozie-tags-remove-size, var(--rtg-remove-size, 1.1rem));
      height: var(--rozie-tags-remove-size, var(--rtg-remove-size, 1.1rem));
      padding: 0;
      font: inherit;
      line-height: 1;
      color: var(--rozie-tags-remove-color, var(--rtg-remove-color, currentColor));
      background: transparent;
      border: none;
      border-radius: 50%;
      cursor: pointer;
      opacity: var(--rozie-tags-remove-opacity, var(--rtg-remove-opacity, 0.65));
      transition: opacity 0.15s, background 0.15s;
    }
    .rozie-tags-chip__remove:hover:not(:disabled) {
      opacity: 1;
      background: var(--rozie-tags-remove-hover-bg, var(--rtg-remove-hover-bg, rgba(0, 0, 0, 0.1)));
    }
    .rozie-tags-chip__remove:disabled {
      cursor: not-allowed;
      opacity: 0.4;
    }
    .rozie-tags-input {
      flex: 1 1 var(--rozie-tags-input-min, var(--rtg-input-min, 4rem));
      min-width: var(--rozie-tags-input-min, var(--rtg-input-min, 4rem));
      padding: var(--rozie-tags-input-padding, var(--rtg-input-padding, 0.15rem 0.1rem));
      font: inherit;
      color: var(--rozie-tags-color, var(--rtg-color, inherit));
      background: transparent;
      border: none;
      outline: none;
    }
    .rozie-tags-input::placeholder {
      color: var(--rozie-tags-placeholder-color, var(--rtg-placeholder-color, rgba(0, 0, 0, 0.4)));
    }
    .rozie-tags-input:disabled {
      cursor: not-allowed;
    }
    .rozie-tags-count {
      position: absolute;
      width: 1px;
      height: 1px;
      padding: 0;
      margin: -1px;
      overflow: hidden;
      clip: rect(0, 0, 0, 0);
      white-space: nowrap;
      border: 0;
    }
    .rozie-tags--disabled {
      cursor: not-allowed;
      opacity: var(--rozie-tags-disabled-opacity, var(--rtg-disabled-opacity, 0.6));
      background: var(--rozie-tags-disabled-bg, var(--rtg-disabled-bg, rgba(0, 0, 0, 0.04)));
    }

    @media (prefers-color-scheme: dark) {
        ::ng-deep :where(:root:not(.light):not([data-theme="light"])) {
          --rtg-bg: #1e293b;
          --rtg-border-color: rgba(255, 255, 255, 0.16);
          --rtg-accent: #60a5fa;
          --rtg-focus-ring-color: rgba(96, 165, 250, 0.35);
          --rtg-chip-bg: rgba(96, 165, 250, 0.22);
          --rtg-remove-hover-bg: rgba(255, 255, 255, 0.14);
          --rtg-placeholder-color: rgba(255, 255, 255, 0.45);
          --rtg-disabled-bg: rgba(255, 255, 255, 0.06);
        }
      }
  `],
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => Tags),
      multi: true,
    },
  ],
  host: { '(focusout)': '__rozieCvaOnTouched()' },
})
export class Tags {
  /**
   * The committed tokens — `model: true`, so a commit/remove/paste writes a **fresh** array back through `r-model:modelValue` (uncontrolled fallback `[]`). Because it is the sole model prop, the Angular output is a `ControlValueAccessor` (`[formControl]` / `[(ngModel)]` bind directly).
   * @example
   * <rozie-tags [(modelValue)]="skills" placeholder="Add a skill…" />
   */
  modelValue = model<any[]>((() => [])());
  /**
   * The keys that commit the current draft as a token (matched against the key event's `key`). Default `[',', 'Enter']`. Non-`'Enter'` entries also act as the split characters when pasting bulk text: a paste containing one is split and every part is added, and the parts that are rejected (by `validate` or `max`) are inserted at the caret, so the typed draft is kept. A paste with no split character is ordinary text. Use e.g. `[' ', 'Enter']` for a space-delimited input.
   */
  delimiters = input<any[]>((() => [',', 'Enter'])());
  /**
   * Allow the same token value to be added more than once. Defaults to `false` — a candidate equal (case-sensitive) to an existing token is silently rejected on commit. Set `true` to permit duplicates.
   */
  allowDuplicates = input<boolean>(false);
  /**
   * Maximum number of tokens. Once the list reaches `max`, the input is disabled and further adds (type, paste, programmatic) are rejected. `null` (the default) means unlimited.
   */
  max = input<(number) | null>(null);
  /**
   * Disable the whole control — the text input is disabled, every remove button is disabled, and no token can be added or removed. Also sets the Angular CVA disabled state.
   */
  disabled = input<boolean>(false);
  /**
   * Render the tokens read-only — they remain visible but cannot be added or removed, and the text input is hidden. Unlike `disabled` it carries no disabled styling, so it reads as a display of committed values.
   */
  readonly = input<boolean>(false);
  /**
   * Optional per-token validator / normalizer. Called with `(candidate, tokens)` for each commit; return a (possibly normalized) **string** to accept it, or a falsy value (`false` / `null` / `""`) to reject the candidate. Runs before the dedup + `max` checks. Example: `v => /^\S+@\S+$/.test(v) ? v.toLowerCase() : false` for emails.
   * @example
   * validate: (v) => (v.length >= 2 ? v.trim() : false)
   */
  validate = input<((...args: any[]) => any) | null>(null);
  /**
   * Placeholder text for the inline text input (e.g. `"Add a tag…"`).
   */
  placeholder = input<string>('');
  /**
   * Accessible name for the whole control (`role="group"`). The inline text input is labelled with the same name so assistive tech announces what is being entered. A visually-hidden live region announces the current token count on change.
   */
  ariaLabel = input<(string) | null>(null);
  draft = signal('');
  root = viewChild<ElementRef<HTMLDivElement>>('root');
  change = output<unknown>();
  add = output<unknown>();
  remove = output<unknown>();
  @ContentChild('tag', { read: TemplateRef }) tagTpl?: TemplateRef<TagCtx>;
  templates = input<Record<string, TemplateRef<unknown>> | undefined>(undefined);
  __rozieFills = contentChildren(RozieSlot, { descendants: true });
  __rozieFillMap = computed(() => {
    const map = Object.create(null) as Record<string, TemplateRef<unknown>>;
    for (const f of this.__rozieFills()) {
      const k = f.rozieSlot();
      if (k == null) continue;
      if (k === '__proto__' || k === 'constructor' || k === 'prototype') continue;
      map[k === '' ? 'defaultSlot' : k] = f.templateRef;
    }
    return map;
  });

  // ---- derived view (plain functions, uniform ×6) ------------------------
  // The committed tokens, normalized to a string[].
  tokens = () => Array.isArray(this.modelValue()) ? this.modelValue() : [];
  // The configured commit keys, normalized to a string[].
  commitKeys = () => Array.isArray(this.delimiters()) ? this.delimiters() : [',', 'Enter'];
  // The non-Enter delimiters act as split characters for paste.
  splitChars = () => this.commitKeys().filter((k: any) => k !== 'Enter');
  // Whether the control has reached its token cap.
  atMax = () => typeof this.max() === 'number' && this.tokens().length >= this.max();
  // Whether new input is accepted at all.
  canEdit = () => !(this.disabled() || this.__rozieCvaDisabled()) && !this.readonly();
  // ---- write funnel (single $emit site) ----------------------------------
  // Write the model and emit change. Every committed-list mutation funnels here.
  commitTokens = (next: any) => {
    this.modelValue.set(next), this.__rozieCvaOnChange(next);
    this.change.emit({
      value: next
    });
  };
  // ---- add / remove ------------------------------------------------------
  // Normalize → validate → dedup → cap ONE candidate against the running list
  // `cur`. Returns `{ value }` to add, or `value: null` with a reason: 'duplicate' (already a
  // token — dropping it loses nothing) or 'rejected' (empty, invalid or over the
  // cap).
  candidateFor = (raw: any, cur: any) => {
    const __validate = this.validate();
    const __max = this.max();
    let candidate = String(raw == null ? '' : raw).trim();
    if (!candidate) return {
      value: null,
      reject: 'rejected'
    };
    if (typeof __validate === 'function') {
      const result = __validate(candidate, cur);
      if (!result) return {
        value: null,
        reject: 'rejected'
      };
      candidate = String(result);
      if (!candidate) return {
        value: null,
        reject: 'rejected'
      };
    }
    if (!this.allowDuplicates() && cur.indexOf(candidate) !== -1) return {
      value: null,
      reject: 'duplicate'
    };
    if (typeof __max === 'number' && cur.length >= __max) return {
      value: null,
      reject: 'rejected'
    };
    return {
      value: candidate,
      reject: ''
    };
  };
  // Add every raw candidate in order: ONE model write (commitTokens) with the
  // accumulated list, then one `add` per added token with the running list as of
  // that token. Accumulating locally matters: re-reading `tokens()` between adds
  // in one handler sees the pre-write list on React (and on Vue until the next
  // tick), so a multi-part paste used to keep only its last part. Returns the
  // added tokens and the raw candidates that were rejected (duplicates are neither).
  addTokens = (raws: any) => {
    if (!this.canEdit()) return {
      added: [],
      rejected: raws.slice()
    };
    let next = this.tokens();
    const added = [];
    const snapshots = [];
    const rejected = [];
    for (let i = 0; i < raws.length; i++) {
      const r = this.candidateFor(raws[i], next);
      if (r.value === null) {
        if (r.reject === 'rejected') rejected.push(raws[i]);
        continue;
      }
      next = next.concat([r.value]);
      added.push(r.value);
      snapshots.push(next);
    }
    if (added.length > 0) this.commitTokens(next);
    for (let i = 0; i < added.length; i++) {
      this.add.emit({
        value: added[i],
        tokens: snapshots[i]
      });
    }
    return {
      added,
      rejected
    };
  };
  // Add one candidate. Returns true if it was added (so the caller can clear the
  // draft).
  addToken = (raw: any) => this.addTokens([raw]).added.length === 1;
  // Remove the token at `idx`, commit, and emit remove.
  removeAt = (idx: any) => {
    if (!this.canEdit()) return;
    const cur = this.tokens();
    if (idx < 0 || idx >= cur.length) return;
    const removed = cur[idx];
    const next = cur.slice(0, idx).concat(cur.slice(idx + 1));
    this.commitTokens(next);
    this.remove.emit({
      value: removed,
      index: idx,
      tokens: next
    });
  };
  // ---- focus (container ref, post-mount only) ----------------------------
  // Read $refs.root only here / in $onMount / in $expose verbs (post-mount →
  // ROZ123-safe). querySelector reaches the input inside Lit's shadow root too.
  focusTheInput = () => {
    const root = this.root()?.nativeElement;
    if (!root) return;
    const el = root.querySelector('input');
    if (el) el.focus();
  };
  // ---- input handlers ----------------------------------------------------
  // Mirror the typed text into the draft buffer. Capture the fresh local value
  // (do NOT re-read $data.draft in the same handler — React setState is async and
  // would read the pre-write value).
  onInput = (e: any) => {
    this.draft.set(e && e.target ? e.target.value : '');
  };
  // A delimiter key commits the current draft; Backspace in an empty input
  // deletes the previous token.
  onKeydown = (e: any) => {
    if (!this.canEdit()) return;
    const key = e ? e.key : '';
    const value = e && e.target ? e.target.value : '';
    if (this.commitKeys().indexOf(key) !== -1) {
      if (e) e.preventDefault();
      if (this.addToken(value)) this.draft.set('');
      return;
    }
    if (key === 'Backspace' && value === '') {
      const cur = this.tokens();
      if (cur.length > 0) {
        if (e) e.preventDefault();
        this.removeAt(cur.length - 1);
      }
    }
  };
  // Commit any leftover draft when the input loses focus (a common chips UX).
  onBlur = (e: any) => {
    if (!this.canEdit()) return;
    const value = e && e.target ? e.target.value : '';
    if (value && this.addToken(value)) this.draft.set('');
  };
  // insertAtCaret(el, text): insert `text` into the input at the caret, replacing
  // the selection — what an ordinary paste does — and leave the caret after it.
  // The element is written directly too: Angular skips a `[value]` write when the
  // bound value equals the last RENDERED one.
  insertAtCaret = (el: any, text: any) => {
    const cur = el && typeof el.value === 'string' ? el.value : String(this.draft());
    const start = el && typeof el.selectionStart === 'number' ? el.selectionStart : cur.length;
    const end = el && typeof el.selectionEnd === 'number' ? el.selectionEnd : start;
    const next = cur.slice(0, start) + text + cur.slice(end);
    this.draft.set(next);
    if (el && typeof el.value === 'string' && el.value !== next) el.value = next;
    const caret = start + text.length;
    if (el && typeof el.setSelectionRange === 'function') el.setSelectionRange(caret, caret);
  };
  // Paste: text containing a delimiter character is split on them and bulk-added;
  // the parts that are rejected (invalid, or over `max`) are inserted at the caret
  // as an ordinary paste would be, so the typed draft is kept. Text with no
  // delimiter is an ordinary paste into the draft (the browser handles it).
  onPaste = (e: any) => {
    if (!this.canEdit()) return;
    const text = e && e.clipboardData && e.clipboardData.getData('text') || '';
    const seps = this.splitChars();
    let hasSep = false;
    for (let s = 0; s < seps.length; s++) {
      if (text.indexOf(seps[s]) !== -1) hasSep = true;
    }
    if (!hasSep) return;
    if (e) e.preventDefault();
    let parts = [text];
    // Split on every separator char in turn.
    for (let s = 0; s < seps.length; s++) {
      const sep = seps[s];
      const out = [];
      for (let p = 0; p < parts.length; p++) {
        const pieces = String(parts[p]).split(sep);
        for (let q = 0; q < pieces.length; q++) out.push(pieces[q]);
      }
      parts = out;
    }
    const trimmed = parts.map((p: any) => String(p).trim()).filter((p: any) => p.length > 0);
    const rejected = this.addTokens(trimmed).rejected;
    if (rejected.length > 0) this.insertAtCaret(e ? e.target : null, rejected.join(seps[0] + ' '));
  };
  // ---- per-element attribute helpers -------------------------------------
  removeLabel = (t: any) => 'Remove ' + String(t);
  countLabel = () => {
    const n = this.tokens().length;
    return n === 1 ? '1 tag' : n + ' tags';
  };
  // ---- lifecycle + imperative handle -------------------------------------
  // clear() — remove every token (emits change with []) and focus the input.
  clear = () => {
    this.commitTokens([]);
    this.draft.set('');
    this.focusTheInput();
  };
  // focus() — move DOM focus to the text input. DELIBERATELY overrides the
  // inherited HTMLElement.focus on the Lit custom element (warn-only ROZ137,
  // accepted — the public focus() handle is the intended semantics; otp/slider
  // precedent, consistent with NumberField which also exposes `focus`).
  focus = () => this.focusTheInput();

  private __rozieCvaOnChange: (v: any[]) => void = () => {};
  private __rozieCvaOnTouchedFn: () => void = () => {};
  protected __rozieCvaDisabled = signal(false);

  writeValue(v: any[] | null): void {
    this.modelValue.set(v ?? (() => [])());
  }
  registerOnChange(fn: (v: any[]) => void): void {
    this.__rozieCvaOnChange = fn;
  }
  registerOnTouched(fn: () => void): void {
    this.__rozieCvaOnTouchedFn = fn;
  }
  setDisabledState(isDisabled: boolean): void {
    this.__rozieCvaDisabled.set(isDisabled);
  }
  __rozieCvaOnTouched(): void {
    this.__rozieCvaOnTouchedFn();
  }

  static ngTemplateContextGuard(
    _dir: Tags,
    _ctx: unknown,
  ): _ctx is TagCtx {
    return true;
  }

  private __rozieDestroyRef = inject(DestroyRef);

  private rozieSpread_0 = viewChild<ElementRef>('rozieSpread_0');

  private __rozieApplyAttrs = createRozieAttrApplier(inject(Renderer2));

  private __rozieGetHostAttrs = createRozieHostAttrsReader(inject(ElementRef));

  private __rozieSpread_0_effect = afterRenderEffect(() => {
    const el = this.rozieSpread_0()?.nativeElement;
    if (!el) return;
    this.__rozieApplyAttrs(el, this.__rozieGetHostAttrs());
  });

  private rozieListenersTarget_1 = viewChild<ElementRef>('rozieListenersTarget_1');

  private __rozieListenersRenderer = inject(Renderer2);

  private __rozieListenersDisposers_1: Array<() => void> = [];

  private __rozieListenersDestroyRegistered_1 = false;

  private __rozieListenersEffect_1 = effect(() => {
    const el = this.rozieListenersTarget_1()?.nativeElement;
    if (!el) return;
    for (const off of this.__rozieListenersDisposers_1) off();
    this.__rozieListenersDisposers_1 = [];
    const obj: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(obj)) {
      if (k === '__proto__' || k === 'constructor' || k === 'prototype') continue;
      if (typeof v !== 'function') continue;
      const norm = k.startsWith('on') ? k.slice(2).toLowerCase() : k;
      const dispose = this.__rozieListenersRenderer.listen(el, norm, v as EventListener);
      this.__rozieListenersDisposers_1.push(dispose);
    }
    if (!this.__rozieListenersDestroyRegistered_1) {
      this.__rozieListenersDestroyRegistered_1 = true;
      this.__rozieDestroyRef.onDestroy(() => {
        for (const off of this.__rozieListenersDisposers_1) off();
        this.__rozieListenersDisposers_1 = [];
      });
    }
  });

  private _tag_ctx_2 = (t: any) => ({ $implicit: { tag: t, index: this.tokens().indexOf(t), remove: () => this.removeAt(this.tokens().indexOf(t)) }, tag: t, index: this.tokens().indexOf(t), remove: () => this.removeAt(this.tokens().indexOf(t)) });

  rozieDisplay(v: unknown): string { return __rozieDisplay(v); }

  rozieAttr(v: unknown): string | null { return __rozieAttr(v); }
}

export default Tags;

// packages/ui/tags/packages/vue/src/Tags.vue
<template>

<div :class="['rozie-tags', { 'rozie-tags--disabled': props.disabled, 'rozie-tags--readonly': props.readonly }]" ref="rootRef" role="group" :aria-label="props.ariaLabel" v-bind="$attrs">
  <ul class="rozie-tags-list">
    <li v-for="t in tokens()" :key="t + ':' + tokens().indexOf(t)" class="rozie-tags-chip">
      <slot name="tag" :tag="t" :index="tokens().indexOf(t)" :remove="() => removeAt(tokens().indexOf(t))">
        <span class="rozie-tags-chip__label">{{ t }}</span>
        <button v-if="!props.readonly" type="button" class="rozie-tags-chip__remove" :disabled="!!props.disabled" :aria-label="removeLabel(t)" @click="removeAt(tokens().indexOf(t))">×</button></slot>
    </li>
  </ul>

  <input v-if="!props.readonly" class="rozie-tags-input" type="text" autocomplete="off" autocapitalize="off" :value="draft" :placeholder="props.placeholder" :disabled="!!props.disabled || !!atMax()" :aria-label="props.ariaLabel" :aria-disabled="!!props.disabled" @input="onInput($event)" @keydown="onKeydown($event)" @paste="onPaste($event)" @blur="onBlur($event)" /><span class="rozie-tags-count" aria-live="polite">{{ countLabel() }}</span>
</div>

</template>

<script setup lang="ts">
import { ref } from 'vue';

const props = withDefaults(
  defineProps<{
    /**
     * The keys that commit the current draft as a token (matched against the key event's `key`). Default `[',', 'Enter']`. Non-`'Enter'` entries also act as the split characters when pasting bulk text: a paste containing one is split and every part is added, and the parts that are rejected (by `validate` or `max`) are inserted at the caret, so the typed draft is kept. A paste with no split character is ordinary text. Use e.g. `[' ', 'Enter']` for a space-delimited input.
     */
    delimiters?: any[];
    /**
     * Allow the same token value to be added more than once. Defaults to `false` — a candidate equal (case-sensitive) to an existing token is silently rejected on commit. Set `true` to permit duplicates.
     */
    allowDuplicates?: boolean;
    /**
     * Maximum number of tokens. Once the list reaches `max`, the input is disabled and further adds (type, paste, programmatic) are rejected. `null` (the default) means unlimited.
     */
    max?: number | null;
    /**
     * Disable the whole control — the text input is disabled, every remove button is disabled, and no token can be added or removed. Also sets the Angular CVA disabled state.
     */
    disabled?: boolean;
    /**
     * Render the tokens read-only — they remain visible but cannot be added or removed, and the text input is hidden. Unlike `disabled` it carries no disabled styling, so it reads as a display of committed values.
     */
    readonly?: boolean;
    /**
     * Optional per-token validator / normalizer. Called with `(candidate, tokens)` for each commit; return a (possibly normalized) **string** to accept it, or a falsy value (`false` / `null` / `""`) to reject the candidate. Runs before the dedup + `max` checks. Example: `v => /^\S+@\S+$/.test(v) ? v.toLowerCase() : false` for emails.
     * @example
     * validate: (v) => (v.length >= 2 ? v.trim() : false)
     */
    validate?: ((...args: any[]) => any) | null;
    /**
     * Placeholder text for the inline text input (e.g. `"Add a tag…"`).
     */
    placeholder?: string;
    /**
     * Accessible name for the whole control (`role="group"`). The inline text input is labelled with the same name so assistive tech announces what is being entered. A visually-hidden live region announces the current token count on change.
     */
    ariaLabel?: string | null;
  }>(),
  { delimiters: () => [',', 'Enter'], allowDuplicates: false, max: null, disabled: false, readonly: false, validate: null, placeholder: '', ariaLabel: null }
);

/**
 * The committed tokens — `model: true`, so a commit/remove/paste writes a **fresh** array back through `r-model:modelValue` (uncontrolled fallback `[]`). Because it is the sole model prop, the Angular output is a `ControlValueAccessor` (`[formControl]` / `[(ngModel)]` bind directly).
 * @example
 * <Tags v-model:modelValue="skills" placeholder="Add a skill…" />
 */
const modelValue = defineModel<any[]>('modelValue', { default: () => [] });

const emit = defineEmits<{
  change: [...args: any[]];
  add: [...args: any[]];
  remove: [...args: any[]];
}>();

defineSlots<{
  tag(props: { tag: any; index: any; remove: any }): any;
}>();

const draft = ref('');

const rootRef = ref<HTMLElement>();

// ---- derived view (plain functions, uniform ×6) ------------------------
// The committed tokens, normalized to a string[].
const tokens = () => Array.isArray(modelValue.value) ? modelValue.value : [];
// The configured commit keys, normalized to a string[].
const commitKeys = () => Array.isArray(props.delimiters) ? props.delimiters : [',', 'Enter'];
// The non-Enter delimiters act as split characters for paste.
const splitChars = () => commitKeys().filter((k: any) => k !== 'Enter');
// Whether the control has reached its token cap.
const atMax = () => typeof props.max === 'number' && tokens().length >= props.max;
// Whether new input is accepted at all.
const canEdit = () => !props.disabled && !props.readonly;
// ---- write funnel (single $emit site) ----------------------------------
// Write the model and emit change. Every committed-list mutation funnels here.
const commitTokens = (next: any) => {
  modelValue.value = next;
  emit('change', {
    value: next
  });
};
// ---- add / remove ------------------------------------------------------
// Normalize → validate → dedup → cap ONE candidate against the running list
// `cur`. Returns `{ value }` to add, or `value: null` with a reason: 'duplicate' (already a
// token — dropping it loses nothing) or 'rejected' (empty, invalid or over the
// cap).
const candidateFor = (raw: any, cur: any) => {
  let candidate = String(raw == null ? '' : raw).trim();
  if (!candidate) return {
    value: null,
    reject: 'rejected'
  };
  if (typeof props.validate === 'function') {
    const result = props.validate(candidate, cur);
    if (!result) return {
      value: null,
      reject: 'rejected'
    };
    candidate = String(result);
    if (!candidate) return {
      value: null,
      reject: 'rejected'
    };
  }
  if (!props.allowDuplicates && cur.indexOf(candidate) !== -1) return {
    value: null,
    reject: 'duplicate'
  };
  if (typeof props.max === 'number' && cur.length >= props.max) return {
    value: null,
    reject: 'rejected'
  };
  return {
    value: candidate,
    reject: ''
  };
};
// Add every raw candidate in order: ONE model write (commitTokens) with the
// accumulated list, then one `add` per added token with the running list as of
// that token. Accumulating locally matters: re-reading `tokens()` between adds
// in one handler sees the pre-write list on React (and on Vue until the next
// tick), so a multi-part paste used to keep only its last part. Returns the
// added tokens and the raw candidates that were rejected (duplicates are neither).
const addTokens = (raws: any) => {
  if (!canEdit()) return {
    added: [],
    rejected: raws.slice()
  };
  let next = tokens();
  const added = [];
  const snapshots = [];
  const rejected = [];
  for (let i = 0; i < raws.length; i++) {
    const r = candidateFor(raws[i], next);
    if (r.value === null) {
      if (r.reject === 'rejected') rejected.push(raws[i]);
      continue;
    }
    next = next.concat([r.value]);
    added.push(r.value);
    snapshots.push(next);
  }
  if (added.length > 0) commitTokens(next);
  for (let i = 0; i < added.length; i++) {
    emit('add', {
      value: added[i],
      tokens: snapshots[i]
    });
  }
  return {
    added,
    rejected
  };
};
// Add one candidate. Returns true if it was added (so the caller can clear the
// draft).
const addToken = (raw: any) => addTokens([raw]).added.length === 1;
// Remove the token at `idx`, commit, and emit remove.
const removeAt = (idx: any) => {
  if (!canEdit()) return;
  const cur = tokens();
  if (idx < 0 || idx >= cur.length) return;
  const removed = cur[idx];
  const next = cur.slice(0, idx).concat(cur.slice(idx + 1));
  commitTokens(next);
  emit('remove', {
    value: removed,
    index: idx,
    tokens: next
  });
};
// ---- focus (container ref, post-mount only) ----------------------------
// Read $refs.root only here / in $onMount / in $expose verbs (post-mount →
// ROZ123-safe). querySelector reaches the input inside Lit's shadow root too.
const focusTheInput = () => {
  const root = rootRef.value;
  if (!root) return;
  const el = root.querySelector('input');
  if (el) el.focus();
};
// ---- input handlers ----------------------------------------------------
// Mirror the typed text into the draft buffer. Capture the fresh local value
// (do NOT re-read $data.draft in the same handler — React setState is async and
// would read the pre-write value).
const onInput = (e: any) => {
  draft.value = e && e.target ? e.target.value : '';
};
// A delimiter key commits the current draft; Backspace in an empty input
// deletes the previous token.
const onKeydown = (e: any) => {
  if (!canEdit()) return;
  const key = e ? e.key : '';
  const value = e && e.target ? e.target.value : '';
  if (commitKeys().indexOf(key) !== -1) {
    if (e) e.preventDefault();
    if (addToken(value)) draft.value = '';
    return;
  }
  if (key === 'Backspace' && value === '') {
    const cur = tokens();
    if (cur.length > 0) {
      if (e) e.preventDefault();
      removeAt(cur.length - 1);
    }
  }
};
// Commit any leftover draft when the input loses focus (a common chips UX).
const onBlur = (e: any) => {
  if (!canEdit()) return;
  const value = e && e.target ? e.target.value : '';
  if (value && addToken(value)) draft.value = '';
};
// insertAtCaret(el, text): insert `text` into the input at the caret, replacing
// the selection — what an ordinary paste does — and leave the caret after it.
// The element is written directly too: Angular skips a `[value]` write when the
// bound value equals the last RENDERED one.
const insertAtCaret = (el: any, text: any) => {
  const cur = el && typeof el.value === 'string' ? el.value : String(draft.value);
  const start = el && typeof el.selectionStart === 'number' ? el.selectionStart : cur.length;
  const end = el && typeof el.selectionEnd === 'number' ? el.selectionEnd : start;
  const next = cur.slice(0, start) + text + cur.slice(end);
  draft.value = next;
  if (el && typeof el.value === 'string' && el.value !== next) el.value = next;
  const caret = start + text.length;
  if (el && typeof el.setSelectionRange === 'function') el.setSelectionRange(caret, caret);
};
// Paste: text containing a delimiter character is split on them and bulk-added;
// the parts that are rejected (invalid, or over `max`) are inserted at the caret
// as an ordinary paste would be, so the typed draft is kept. Text with no
// delimiter is an ordinary paste into the draft (the browser handles it).
const onPaste = (e: any) => {
  if (!canEdit()) return;
  const text = e && e.clipboardData && e.clipboardData.getData('text') || '';
  const seps = splitChars();
  let hasSep = false;
  for (let s = 0; s < seps.length; s++) {
    if (text.indexOf(seps[s]) !== -1) hasSep = true;
  }
  if (!hasSep) return;
  if (e) e.preventDefault();
  let parts = [text];
  // Split on every separator char in turn.
  for (let s = 0; s < seps.length; s++) {
    const sep = seps[s];
    const out = [];
    for (let p = 0; p < parts.length; p++) {
      const pieces = String(parts[p]).split(sep);
      for (let q = 0; q < pieces.length; q++) out.push(pieces[q]);
    }
    parts = out;
  }
  const trimmed = parts.map((p: any) => String(p).trim()).filter((p: any) => p.length > 0);
  const rejected = addTokens(trimmed).rejected;
  if (rejected.length > 0) insertAtCaret(e ? e.target : null, rejected.join(seps[0] + ' '));
};
// ---- per-element attribute helpers -------------------------------------
const removeLabel = (t: any) => 'Remove ' + String(t);
const countLabel = () => {
  const n = tokens().length;
  return n === 1 ? '1 tag' : n + ' tags';
};
// ---- lifecycle + imperative handle -------------------------------------
// clear() — remove every token (emits change with []) and focus the input.
const clear = () => {
  commitTokens([]);
  draft.value = '';
  focusTheInput();
};
// focus() — move DOM focus to the text input. DELIBERATELY overrides the
// inherited HTMLElement.focus on the Lit custom element (warn-only ROZ137,
// accepted — the public focus() handle is the intended semantics; otp/slider
// precedent, consistent with NumberField which also exposes `focus`).
const focus = () => focusTheInput();

defineExpose({ clear, focus });
</script>

<style scoped>
.rozie-tags {
  display: inline-flex;
  flex-wrap: wrap;
  align-items: center;
  gap: var(--rozie-tags-gap, var(--rtg-gap, 0.4rem));
  padding: var(--rozie-tags-padding, var(--rtg-padding, 0.35rem 0.45rem));
  font: var(--rozie-tags-font, inherit);
  background: var(--rozie-tags-bg, var(--rtg-bg, #fff));
  border: var(--rozie-tags-border-width, var(--rtg-border-width, 1px)) solid var(--rozie-tags-border-color, var(--rtg-border-color, rgba(0, 0, 0, 0.25)));
  border-radius: var(--rozie-tags-radius, var(--rtg-radius, 0.5rem));
  min-width: var(--rozie-tags-min-width, var(--rtg-min-width, 12rem));
}
.rozie-tags:focus-within {
  border-color: var(--rozie-tags-accent, var(--rtg-accent, #0066cc));
  box-shadow: 0 0 0 var(--rozie-tags-focus-ring-width, var(--rtg-focus-ring-width, 3px)) var(--rozie-tags-focus-ring-color, var(--rtg-focus-ring-color, rgba(0, 102, 204, 0.25)));
}
.rozie-tags-list {
  display: contents;
  margin: 0;
  padding: 0;
  list-style: none;
}
.rozie-tags-chip {
  display: inline-flex;
  align-items: center;
  gap: var(--rozie-tags-chip-gap, var(--rtg-chip-gap, 0.3rem));
  padding: var(--rozie-tags-chip-padding, var(--rtg-chip-padding, 0.15rem 0.5rem));
  font-size: var(--rozie-tags-chip-font-size, var(--rtg-chip-font-size, 0.85rem));
  color: var(--rozie-tags-chip-color, var(--rtg-chip-color, inherit));
  background: var(--rozie-tags-chip-bg, var(--rtg-chip-bg, rgba(0, 102, 204, 0.12)));
  border-radius: var(--rozie-tags-chip-radius, var(--rtg-chip-radius, 0.375rem));
  white-space: nowrap;
}
.rozie-tags-chip__remove {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: var(--rozie-tags-remove-size, var(--rtg-remove-size, 1.1rem));
  height: var(--rozie-tags-remove-size, var(--rtg-remove-size, 1.1rem));
  padding: 0;
  font: inherit;
  line-height: 1;
  color: var(--rozie-tags-remove-color, var(--rtg-remove-color, currentColor));
  background: transparent;
  border: none;
  border-radius: 50%;
  cursor: pointer;
  opacity: var(--rozie-tags-remove-opacity, var(--rtg-remove-opacity, 0.65));
  transition: opacity 0.15s, background 0.15s;
}
.rozie-tags-chip__remove:hover:not(:disabled) {
  opacity: 1;
  background: var(--rozie-tags-remove-hover-bg, var(--rtg-remove-hover-bg, rgba(0, 0, 0, 0.1)));
}
.rozie-tags-chip__remove:disabled {
  cursor: not-allowed;
  opacity: 0.4;
}
.rozie-tags-input {
  flex: 1 1 var(--rozie-tags-input-min, var(--rtg-input-min, 4rem));
  min-width: var(--rozie-tags-input-min, var(--rtg-input-min, 4rem));
  padding: var(--rozie-tags-input-padding, var(--rtg-input-padding, 0.15rem 0.1rem));
  font: inherit;
  color: var(--rozie-tags-color, var(--rtg-color, inherit));
  background: transparent;
  border: none;
  outline: none;
}
.rozie-tags-input::placeholder {
  color: var(--rozie-tags-placeholder-color, var(--rtg-placeholder-color, rgba(0, 0, 0, 0.4)));
}
.rozie-tags-input:disabled {
  cursor: not-allowed;
}
.rozie-tags-count {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  white-space: nowrap;
  border: 0;
}
.rozie-tags--disabled {
  cursor: not-allowed;
  opacity: var(--rozie-tags-disabled-opacity, var(--rtg-disabled-opacity, 0.6));
  background: var(--rozie-tags-disabled-bg, var(--rtg-disabled-bg, rgba(0, 0, 0, 0.04)));
}
</style>

<style>
@media (prefers-color-scheme: dark) {
    :where(:root:not(.light):not([data-theme="light"])) {
      --rtg-bg: #1e293b;
      --rtg-border-color: rgba(255, 255, 255, 0.16);
      --rtg-accent: #60a5fa;
      --rtg-focus-ring-color: rgba(96, 165, 250, 0.35);
      --rtg-chip-bg: rgba(96, 165, 250, 0.22);
      --rtg-remove-hover-bg: rgba(255, 255, 255, 0.14);
      --rtg-placeholder-color: rgba(255, 255, 255, 0.45);
      --rtg-disabled-bg: rgba(255, 255, 255, 0.06);
    }
  }
</style>
