// packages/ui/data-table/packages/angular/src/Column.ts
import { Component, DestroyRef, ViewEncapsulation, effect, inject, input, untracked } from '@angular/core';
import { rozieToken } from '@rozie/runtime-angular';

@Component({
  selector: 'rozie-column',
  standalone: true,
  template: `


    <div class="rozie-data-table-column" style="display:none"></div>

  `,
  styles: [`
    :host(rozie-column) { display: contents; }
  `],
})
export class Column {
  /**
   * The column id. Optional — defaults to `field` when omitted. Used as the key in the id-keyed registry union and in the `#cell` / `#colHeader` slot dispatch.
   */
  id = input<string>('');
  /**
   * The row field this column reads (table-core `accessorKey`). The plain accessor value renders when the `#cell` slot falls through.
   * @example
   * <rozie-column field="email" header="Email" />
   */
  field = input<string>('');
  /**
   * The header label, rendered when the parent `#colHeader` slot falls through to the plain label.
   */
  header = input<string>('');
  /**
   * Whether this column participates in click-to-sort. Default `false`. Bind `:sortable="true"` (a bare attr only coerces on Vue+Lit).
   */
  sortable = input<boolean>(false);
  /**
   * Whether this column participates in per-column filtering (the `#filter` slot / faceted filter chrome). Default `false`.
   */
  filterable = input<boolean>(false);
  /**
   * Pin side: `''` (unpinned) | `'left'` | `'right'`. Reserved metadata carried into the parent's column pinning state.
   */
  pinned = input<string>('');
  /**
   * Optional fixed/initial column width — a CSS length string or a px number.
   */
  width = input<string | number>('');
  /**
   * Reserved per-column metadata flagging participation in the expand affordance. The expander chevron is its own auto-injected leading column on `<DataTable expandable>`, so this is forward-compat metadata, not the toggle host. Default `false`.
   */
  expandable = input<boolean>(false);
  /**
   * Whether this column is offered to the headless `#groupBar` as a grouping target. Defaults `true` (opt-OUT via `:groupable="false"`); this only filters the groupable-columns list. Whether grouping is engaged is driven by the parent's `grouping` model, never this flag.
   */
  groupable = input<boolean>(true);
  /**
   * The table-core aggregation for this column inside a group-header cell. Either a built-in name string — `'sum'` | `'min'` | `'max'` | `'extent'` | `'mean'` | `'median'` | `'unique'` | `'uniqueCount'` | `'count'` — or a custom function `(columnId, leafRows, childRows) => any` (defensively wrapped by the parent so a throw cannot crash grouping). Null → no aggregation (the group-header cell renders as a placeholder).
   */
  aggregationFn = input<(string | ((...args: any[]) => any)) | null>(null);
  /**
   * Whether this column's cells are editable (opt-in). Default `false` → the column is read-only and the display↔editor branch never mounts an editor. Bind `:editable="true"` (a bare attr only coerces on Vue+Lit).
   */
  editable = input<boolean>(false);
  /**
   * Built-in editor type for this column: `'text'` | `'number'` | `'select'` | `'checkbox'`. Ignored when a custom `#editor` scoped slot handles the column. Default `'text'`.
   */
  editor = input<string>('text');
  /**
   * Options for `editor: 'select'` — `[{ value, label }]`. Empty for other editor types.
   */
  editorOptions = input<any[]>((() => [])());
  /**
   * Synchronous per-column validator `(value, row) => true | string`. A string return is the error message (the editor stays open and the aria-live region announces it). Null → no validation. The parent wraps it defensively against a thrown/non-bool/non-string return.
   */
  validate = input<((...args: any[]) => any) | null>(null);
  registry = inject(rozieToken('data-table:columns'));
  private __rozieDestroyRef = inject(DestroyRef);
  private __rozieWatchInitial_0 = true;

  constructor() {
    this.reg = this.registry;

    // idempotency flag so a reactive late-context registration (Lit async first paint,
    // REQ-30) and the $onMount registration never double-register the column.
    effect(() => () => {
      if (this.registered) return;
      const live = this.registry;
      if (live == null) return;
      this.reg = live;
      this.registered = true;
      this.reg.registerColumn(this.colId(), this.buildSpec());
    });
    effect(() => { const __watchVal = (() => [this.id(), this.field(), this.header(), this.sortable(), this.filterable(), this.pinned(), this.width(), this.expandable(), this.groupable(), this.aggregationFn(), this.editable(), this.editor(), this.editorOptions(), this.validate()])(); untracked(() => { if (this.__rozieWatchInitial_0) { this.__rozieWatchInitial_0 = false; return; } (() => {
      if (this.reg) this.reg.registerColumn(this.colId(), this.buildSpec());
    })(); }); });
  }

  ngAfterViewInit() {
    // register this column's spec. On Lit the injected registry may still be undefined
    // here (REQ-30 async context); the $onUpdate below performs the registration once
    // the value arrives.
    if (this.reg && !this.registered) {
      this.registered = true;
      this.reg.registerColumn(this.colId(), this.buildSpec());
    }
    this.__rozieDestroyRef.onDestroy(() => {
      if (this.reg) this.reg.unregisterColumn(this.colId());
    });
  }

  reg: any = null;
  registered = false;
  colId = () => this.id() !== '' ? this.id() : this.field();
  buildSpec = () => ({
    id: this.colId(),
    field: this.field() !== '' ? this.field() : this.colId(),
    header: this.header(),
    sortable: this.sortable(),
    filterable: this.filterable(),
    pinned: this.pinned(),
    width: this.width(),
    // Expandable-rows reserved metadata (phase 50, D-04) — carried via the parent registry.
    expandable: this.expandable(),
    // Grouping + aggregation metadata (phase 50, reqs 4-7, D-05) — carried via the parent
    // registry; the parent resolves aggregationFn onto the ColumnDef (defensive-wrapping a
    // custom fn) and filters groupableColumns by `groupable`.
    groupable: this.groupable(),
    aggregationFn: this.aggregationFn(),
    // Editable-cell config (Phase 51) — carried into ColumnDef.meta via the parent
    // registry (the existing per-column metadata path; NO parallel registry).
    editable: this.editable(),
    editor: this.editor(),
    editorOptions: this.editorOptions(),
    validate: this.validate()
  });
}

export default Column;

// packages/ui/data-table/packages/react/src/Column.tsx
import { useCallback, useContext, useEffect, useRef, useState } from 'react';
import { rozieContext } from '@rozie/runtime-react';

interface ColumnProps {
  /**
   * The column id. Optional — defaults to `field` when omitted. Used as the key in the id-keyed registry union and in the `#cell` / `#colHeader` slot dispatch.
   */
  id?: string;
  /**
   * The row field this column reads (table-core `accessorKey`). The plain accessor value renders when the `#cell` slot falls through.
   * @example
   * <Column field="email" header="Email" />
   */
  field?: string;
  /**
   * The header label, rendered when the parent `#colHeader` slot falls through to the plain label.
   */
  header?: string;
  /**
   * Whether this column participates in click-to-sort. Default `false`. Bind `:sortable="true"` (a bare attr only coerces on Vue+Lit).
   */
  sortable?: boolean;
  /**
   * Whether this column participates in per-column filtering (the `#filter` slot / faceted filter chrome). Default `false`.
   */
  filterable?: boolean;
  /**
   * Pin side: `''` (unpinned) | `'left'` | `'right'`. Reserved metadata carried into the parent's column pinning state.
   */
  pinned?: string;
  /**
   * Optional fixed/initial column width — a CSS length string or a px number.
   */
  width?: string | number;
  /**
   * Reserved per-column metadata flagging participation in the expand affordance. The expander chevron is its own auto-injected leading column on `<DataTable expandable>`, so this is forward-compat metadata, not the toggle host. Default `false`.
   */
  expandable?: boolean;
  /**
   * Whether this column is offered to the headless `#groupBar` as a grouping target. Defaults `true` (opt-OUT via `:groupable="false"`); this only filters the groupable-columns list. Whether grouping is engaged is driven by the parent's `grouping` model, never this flag.
   */
  groupable?: boolean;
  /**
   * The table-core aggregation for this column inside a group-header cell. Either a built-in name string — `'sum'` | `'min'` | `'max'` | `'extent'` | `'mean'` | `'median'` | `'unique'` | `'uniqueCount'` | `'count'` — or a custom function `(columnId, leafRows, childRows) => any` (defensively wrapped by the parent so a throw cannot crash grouping). Null → no aggregation (the group-header cell renders as a placeholder).
   */
  aggregationFn?: (string | ((...args: any[]) => any)) | null;
  /**
   * Whether this column's cells are editable (opt-in). Default `false` → the column is read-only and the display↔editor branch never mounts an editor. Bind `:editable="true"` (a bare attr only coerces on Vue+Lit).
   */
  editable?: boolean;
  /**
   * Built-in editor type for this column: `'text'` | `'number'` | `'select'` | `'checkbox'`. Ignored when a custom `#editor` scoped slot handles the column. Default `'text'`.
   */
  editor?: string;
  /**
   * Options for `editor: 'select'` — `[{ value, label }]`. Empty for other editor types.
   */
  editorOptions?: any[];
  /**
   * Synchronous per-column validator `(value, row) => true | string`. A string return is the error message (the editor stays open and the aria-live region announces it). Null → no validation. The parent wraps it defensively against a thrown/non-bool/non-string return.
   */
  validate?: ((...args: any[]) => any) | null;
}

export default function Column(_props: ColumnProps): JSX.Element {
  const registry = useContext(rozieContext("data-table:columns"));
  const __defaultEditorOptions = useState(() => (() => [])())[0];
  const props: Omit<ColumnProps, 'id' | 'field' | 'header' | 'sortable' | 'filterable' | 'pinned' | 'width' | 'expandable' | 'groupable' | 'aggregationFn' | 'editable' | 'editor' | 'editorOptions' | 'validate'> & { id: string; field: string; header: string; sortable: boolean; filterable: boolean; pinned: string; width: string | number; expandable: boolean; groupable: boolean; aggregationFn: (string | ((...args: any[]) => any)) | null; editable: boolean; editor: string; editorOptions: any[]; validate: ((...args: any[]) => any) | null } = {
    ..._props,
    id: _props.id ?? '',
    field: _props.field ?? '',
    header: _props.header ?? '',
    sortable: _props.sortable ?? false,
    filterable: _props.filterable ?? false,
    pinned: _props.pinned ?? '',
    width: _props.width ?? '',
    expandable: _props.expandable ?? false,
    groupable: _props.groupable ?? true,
    aggregationFn: _props.aggregationFn ?? null,
    editable: _props.editable ?? false,
    editor: _props.editor ?? 'text',
    editorOptions: _props.editorOptions ?? __defaultEditorOptions,
    validate: _props.validate ?? null,
  };
  const reg = useRef<any>(null);
  const registered = useRef(false);
  const _watch0First = useRef(true);

  reg.current = registry;

  // idempotency flag so a reactive late-context registration (Lit async first paint,
  // REQ-30) and the $onMount registration never double-register the column.
  const colId = useCallback(() => props.id !== '' ? props.id : props.field, [props.field, props.id]);
  const buildSpec = useCallback(() => ({
    id: colId(),
    field: props.field !== '' ? props.field : colId(),
    header: props.header,
    sortable: props.sortable,
    filterable: props.filterable,
    pinned: props.pinned,
    width: props.width,
    // Expandable-rows reserved metadata (phase 50, D-04) — carried via the parent registry.
    expandable: props.expandable,
    // Grouping + aggregation metadata (phase 50, reqs 4-7, D-05) — carried via the parent
    // registry; the parent resolves aggregationFn onto the ColumnDef (defensive-wrapping a
    // custom fn) and filters groupableColumns by `groupable`.
    groupable: props.groupable,
    aggregationFn: props.aggregationFn,
    // Editable-cell config (Phase 51) — carried into ColumnDef.meta via the parent
    // registry (the existing per-column metadata path; NO parallel registry).
    editable: props.editable,
    editor: props.editor,
    editorOptions: props.editorOptions,
    validate: props.validate
  }), [colId, props.aggregationFn, props.editable, props.editor, props.editorOptions, props.expandable, props.field, props.filterable, props.groupable, props.header, props.pinned, props.sortable, props.validate, props.width]);

  useEffect(() => {
    // register this column's spec. On Lit the injected registry may still be undefined
    // here (REQ-30 async context); the $onUpdate below performs the registration once
    // the value arrives.
    if (reg.current && !registered.current) {
      registered.current = true;
      reg.current.registerColumn(colId(), buildSpec());
    }
    return () => {
      if (reg.current) reg.current.unregisterColumn(colId());
    };
  }, []); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => {
    if (registered.current) return;
    const live = registry;
    if (live == null) return;
    reg.current = live;
    registered.current = true;
    reg.current.registerColumn(colId(), buildSpec());
  }, [buildSpec, colId, reg, registered, registry]);
  useEffect(() => {
    if (_watch0First.current) { _watch0First.current = false; return; }
    if (reg.current) reg.current.registerColumn(colId(), buildSpec());
  }, [props.aggregationFn, props.editable, props.editor, props.editorOptions, props.expandable, props.field, props.filterable, props.groupable, props.header, props.id, props.pinned, props.sortable, props.validate, props.width]); // eslint-disable-line react-hooks/exhaustive-deps

  return (
    <>

    <div className={"rozie-data-table-column"} style={{ display: "none" }} data-rozie-s-289f2d72="" />
    </>
  );
}
