// packages/ui/rete/packages/lit/src/Port.ts
import { LitElement, css, html } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { SignalWatcher } from '@lit-labs/preact-signals';
import { ContextConsumer, createContext } from '@lit/context';

const __rozieCtx_rete_nodeType = createContext(Symbol.for("rozie:rete:nodeType"));

@customElement('rozie-port')
export default class Port extends SignalWatcher(LitElement) {
  static styles = css`
:host{display:contents}
`;

  /**
   * Declares an OUTPUT port and names its key — set this (not `input`) so the port direction resolves to `output`. The attribute is `output`, not `out`: `out`/`in` are awkward bare identifiers, so `output`/`input` are used across all six targets.
   * @example
   * <rozie-port output="num" type="number"></rozie-port>
   */
  @property({ type: String, reflect: true }) output?: string;
  /**
   * Declares an INPUT port and names its key — set this (not `output`) so the port direction resolves to `input`. The attribute is `input`, not `in`: `in` is a JS reserved word that Svelte's mandatory `$props()` destructure rejects, so `input`/`output` are used instead.
   */
  @property({ type: String, reflect: true }) input?: string;
  /**
   * The port TYPE — drives the canvas's typed-socket `:validate-types` (a type-mismatched connection is auto-rejected). It is the typed layer, NOT socket identity (a single shared Socket gates identity). Optional: an untyped port imposes no type constraint and connects to anything.
   */
  @property({ type: String, reflect: true }) type?: string;
  /**
   * Optional socket label shown next to the port (defaults to the port key when omitted).
   */
  @property({ type: String, reflect: true }) label?: string;
  /**
   * Allow multiple connections into/out of this socket. Left undefined by default to preserve the canvas's side asymmetry: outputs default to multi, inputs default to single. To force an explicit multi input, use the bare `multiple` attribute (`<Port ... multiple />`) — it resolves to `true` on all six targets.
   */
  @property({ type: Object }) multiple?: unknown;
  /**
   * Visual placement of the socket on the node: `left`, `right`, `top`, or `bottom`. Defaults by direction (input → left, output → right). `top`/`bottom` enable vertical flows (decision trees, top-down pipelines) — the canvas lays the socket out on that edge and the connection anchor shifts onto the matching axis.
   */
  @property({ type: String, reflect: true }) position?: string;
private __rozieCtxConsumer_rete_nodeType = new ContextConsumer(this, { context: __rozieCtx_rete_nodeType, subscribe: true });
private get injectedType() { return this.__rozieCtxConsumer_rete_nodeType.value; }

  private _disconnectCleanups: Array<() => void> = [];
  // Re-parenting guard: set true once the deferred teardown has actually
  // run (a genuine un-mount), so a subsequent reconnect knows to re-arm.
  private _rozieTornDown = false;

  firstUpdated(): void {
    this.nt = this.injectedType;

    // register this typed port against the enclosing node TYPE's schema; the canvas's
    // reconcileNodes builds buildNode with the updated input/output spec for every node
    // of that type. On Lit the injected nodeType ctx may still be undefined here (async
    // context, REQ-30) — the $onUpdate below adds the port once it resolves.
    if (this.nt && !this.added) {
      this.added = true;
      this.nt.addPort(this.portSide(), this.portKey(), this.type, this.label, this.multiple, this.position);
    }
  }

  updated(changedProperties: Map<string, unknown>): void {
    if (this.added) return;
    const live = this.injectedType;
    if (live == null) return;
    this.nt = live;
    this.added = true;
    this.nt.addPort(this.portSide(), this.portKey(), this.type, this.label, this.multiple, this.position);
  }

  disconnectedCallback(): void {
    super.disconnectedCallback();
    queueMicrotask(() => {
      if (this.isConnected || this._rozieTornDown) return;
      this._rozieTornDown = true;
      for (const fn of this._disconnectCleanups) fn();
      this._disconnectCleanups = [];
    });
  }

  render() {
    return html``;
  }

  // $inject is typed `unknown` (Phase 36 D-4), which the STRICT BUNDLED-LEAF tsc
  // rejects on `.addPort(...)` (TS2339). The .rozie-native fix is the null-let → `any`
  // typeNeutralize idiom: alias through a MODULE-SCOPE `let nt = null` so it is in
  // scope from the Solid hoisted onCleanup teardown (the MapLibre Source/Layer
  // lesson). ZERO emitter change.
  nt: any = null;

  // Derive side + key from which of output=/input= is set. output wins if both are
  // (mis)set. `output`/`input` are ordinary identifiers (NOT reserved words) so they
  // read normally — no member-access-only workaround needed. null key (neither set) ⇒
  // addPort no-ops on the canvas side (key == null guard).
  portSide = () => this.output != null ? 'output' : 'input';

  portKey = () => this.output != null ? this.output : this.input;

  // idempotency flag so the $onMount addPort and the late-context $onUpdate path
  // (Lit async, REQ-30) never double-add the port. (addTypePort is also idempotent —
  // same `type::side::key` key, same value — so this is belt-and-suspenders.)
  added = false;
}

// packages/ui/rete/packages/svelte/src/Port.svelte
<script lang="ts">
import { getContext, onMount } from 'svelte';

interface Props {
  /**
   * Declares an OUTPUT port and names its key — set this (not `input`) so the port direction resolves to `output`. The attribute is `output`, not `out`: `out`/`in` are awkward bare identifiers, so `output`/`input` are used across all six targets.
   * @example
   * <Port output="num" type="number" />
   */
  output?: string;
  /**
   * Declares an INPUT port and names its key — set this (not `output`) so the port direction resolves to `input`. The attribute is `input`, not `in`: `in` is a JS reserved word that Svelte's mandatory `$props()` destructure rejects, so `input`/`output` are used instead.
   */
  input?: string;
  /**
   * The port TYPE — drives the canvas's typed-socket `:validate-types` (a type-mismatched connection is auto-rejected). It is the typed layer, NOT socket identity (a single shared Socket gates identity). Optional: an untyped port imposes no type constraint and connects to anything.
   */
  type?: string;
  /**
   * Optional socket label shown next to the port (defaults to the port key when omitted).
   */
  label?: string;
  /**
   * Allow multiple connections into/out of this socket. Left undefined by default to preserve the canvas's side asymmetry: outputs default to multi, inputs default to single. To force an explicit multi input, use the bare `multiple` attribute (`<Port ... multiple />`) — it resolves to `true` on all six targets.
   */
  multiple?: unknown;
  /**
   * Visual placement of the socket on the node: `left`, `right`, `top`, or `bottom`. Defaults by direction (input → left, output → right). `top`/`bottom` enable vertical flows (decision trees, top-down pipelines) — the canvas lays the socket out on that edge and the connection anchor shifts onto the matching axis.
   */
  position?: string;
}

let {
  output = undefined,
  input = undefined,
  type = undefined,
  label = undefined,
  multiple = undefined,
  position = undefined
}: Props = $props();

const injectedType = getContext('rete:nodeType');

// $inject is typed `unknown` (Phase 36 D-4), which the STRICT BUNDLED-LEAF tsc
// rejects on `.addPort(...)` (TS2339). The .rozie-native fix is the null-let → `any`
// typeNeutralize idiom: alias through a MODULE-SCOPE `let nt = null` so it is in
// scope from the Solid hoisted onCleanup teardown (the MapLibre Source/Layer
// lesson). ZERO emitter change.
let nt: any = null;
nt = injectedType;

// Derive side + key from which of output=/input= is set. output wins if both are
// (mis)set. `output`/`input` are ordinary identifiers (NOT reserved words) so they
// read normally — no member-access-only workaround needed. null key (neither set) ⇒
// addPort no-ops on the canvas side (key == null guard).
// Derive side + key from which of output=/input= is set. output wins if both are
// (mis)set. `output`/`input` are ordinary identifiers (NOT reserved words) so they
// read normally — no member-access-only workaround needed. null key (neither set) ⇒
// addPort no-ops on the canvas side (key == null guard).
const portSide = () => output != null ? 'output' : 'input';
const portKey = () => output != null ? output : input;

// idempotency flag so the $onMount addPort and the late-context $onUpdate path
// (Lit async, REQ-30) never double-add the port. (addTypePort is also idempotent —
// same `type::side::key` key, same value — so this is belt-and-suspenders.)
// idempotency flag so the $onMount addPort and the late-context $onUpdate path
// (Lit async, REQ-30) never double-add the port. (addTypePort is also idempotent —
// same `type::side::key` key, same value — so this is belt-and-suspenders.)
let added = false;

onMount(() => {
  // register this typed port against the enclosing node TYPE's schema; the canvas's
  // reconcileNodes builds buildNode with the updated input/output spec for every node
  // of that type. On Lit the injected nodeType ctx may still be undefined here (async
  // context, REQ-30) — the $onUpdate below adds the port once it resolves.
  if (nt && !added) {
    added = true;
    nt.addPort(portSide(), portKey(), type, label, multiple, position);
  }
});
$effect(() => (() => {
  if (added) return;
  const live = injectedType;
  if (live == null) return;
  nt = live;
  added = true;
  nt.addPort(portSide(), portKey(), type, label, multiple, position);
})());
</script>

<!-- empty template -->
