// packages/ui/rete/packages/react/src/Connection.tsx
import { useCallback, useContext, useEffect, useRef } from 'react';
import { rozieContext } from '@rozie/runtime-react';

interface ConnectionProps {
  id?: string;
  source: string;
  sourceOutput?: string;
  target: string;
  targetInput?: string;
}

export default function Connection(_props: ConnectionProps): JSX.Element {
  const canvas = useContext(rozieContext("rete:canvas"));
  const props: Omit<ConnectionProps, 'id' | 'sourceOutput' | 'targetInput'> & { id: string; sourceOutput: string; targetInput: string } = {
    ..._props,
    id: _props.id ?? undefined,
    sourceOutput: _props.sourceOutput ?? undefined,
    targetInput: _props.targetInput ?? undefined,
  };
  const attrs: Record<string, unknown> = (() => {
    const { id, source, sourceOutput, target, targetInput, ...rest } = _props as ConnectionProps & Record<string, unknown>;
    void id; void source; void sourceOutput; void target; void targetInput;
    return rest;
  })();
  const connId = useRef<any>(null);
  const cv = useRef<any>(null);
  const registered = useRef(false);

  cv.current = canvas;

  // Effective edge id: explicit prop wins, else the source:out->target:in default
  // (mirrors reconcileConnections so collision dedup is consistent).
  const edgeId = useCallback(() => {
    if (props.id != null) return props.id;
    const srcOut = props.sourceOutput != null ? props.sourceOutput : 'out';
    const tgtIn = props.targetInput != null ? props.targetInput : 'in';
    return `${props.source}:${srcOut}->${props.target}:${tgtIn}`;
  }, [props.id, props.source, props.sourceOutput, props.target, props.targetInput]);
  const buildConn = useCallback(() => ({
    id: connId.current,
    source: props.source,
    sourceOutput: props.sourceOutput,
    target: props.target,
    targetInput: props.targetInput
  }), [props.source, props.sourceOutput, props.target, props.targetInput]);

  useEffect(() => {
    connId.current = edgeId();
    // On Lit the injected canvas may still be undefined here (async context, REQ-30);
    // the $onUpdate below registers once it resolves.
    if (cv.current && !registered.current) {
      registered.current = true;
      cv.current.registerConnection(connId.current, buildConn());
    }
    return () => {
      if (cv.current) cv.current.unregisterConnection(connId.current);
    };
  }, []); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => {
    if (registered.current) return;
    const live = canvas;
    if (live == null) return;
    cv.current = live;
    if (connId.current == null) connId.current = edgeId();
    registered.current = true;
    cv.current.registerConnection(connId.current, buildConn());
  }, [buildConn, canvas, connId, cv, edgeId, registered]);

  return (
    null
  );
}

// packages/ui/rete/packages/angular/src/Connection.ts
import { Component, DestroyRef, InjectionToken, ViewEncapsulation, effect, inject, input } from '@angular/core';

const __rozieTokenRegistry: Map<string, InjectionToken<unknown>> =
  ((globalThis as Record<string, unknown>).__rozieCtx ??= new Map()) as Map<
    string,
    InjectionToken<unknown>
  >;
function rozieToken(key: string): InjectionToken<unknown> {
  let token = __rozieTokenRegistry.get(key);
  if (!token) {
    token = new InjectionToken<unknown>('rozie:' + key);
    __rozieTokenRegistry.set(key, token);
  }
  return token;
}

@Component({
  selector: 'rozie-connection',
  standalone: true,
  template: `

  `,
})
export class Connection {
  id = input<string>(undefined);
  source = input.required<string>();
  sourceOutput = input<string>(undefined);
  target = input.required<string>();
  targetInput = input<string>(undefined);
  canvas = inject(rozieToken('rete:canvas'));
  private __rozieDestroyRef = inject(DestroyRef);

  constructor() {
    this.cv = this.canvas;

    // Effective edge id: explicit prop wins, else the source:out->target:in default
    // (mirrors reconcileConnections so collision dedup is consistent).
    effect(() => () => {
      if (this.registered) return;
      const live = this.canvas;
      if (live == null) return;
      this.cv = live;
      if (this.connId == null) this.connId = this.edgeId();
      this.registered = true;
      this.cv.registerConnection(this.connId, this.buildConn());
    });
  }

  ngAfterViewInit() {
    this.connId = this.edgeId();
    // On Lit the injected canvas may still be undefined here (async context, REQ-30);
    // the $onUpdate below registers once it resolves.
    // On Lit the injected canvas may still be undefined here (async context, REQ-30);
    // the $onUpdate below registers once it resolves.
    if (this.cv && !this.registered) {
      this.registered = true;
      this.cv.registerConnection(this.connId, this.buildConn());
    }
    this.__rozieDestroyRef.onDestroy(() => {
      if (this.cv) this.cv.unregisterConnection(this.connId);
    });
  }

  cv: any = null;
  edgeId = () => {
    const __id = this.id();
    const __sourceOutput = this.sourceOutput();
    const __targetInput = this.targetInput();
    if (__id != null) return __id;
    const srcOut = __sourceOutput != null ? __sourceOutput : 'out';
    const tgtIn = __targetInput != null ? __targetInput : 'in';
    return `${this.source()}:${srcOut}->${this.target()}:${tgtIn}`;
  };
  connId: any = null;
  registered = false;
  buildConn = () => ({
    id: this.connId,
    source: this.source(),
    sourceOutput: this.sourceOutput(),
    target: this.target(),
    targetInput: this.targetInput()
  });
}

export default Connection;
