// packages/targets/lit/src/emit/emitTypes.ts
/**
 * emitTypes (Lit) — Phase 22 Plan 22-04 (typed `.rozie` imports).
 *
 * Emits a sibling Lit `.d.rozie.ts` from an `IRComponent`. Like the Wave-2
 * sibling renderers (vue/svelte/solid in Plan 22-03) it consumes the Plan-02
 * core-shared `renderPropsInterface` for the framework-AGNOSTIC props body, but
 * swaps the default-export idiom to Lit's NOVEL shape (PATTERNS Pattern 2):
 *
 *   - `export default class <Name> extends LitElement { … }` — Lit consumers
 *     `import './Foo.rozie'` for side-effect (the module registers the custom
 *     element); the value they care about typing is the ELEMENT class, not a
 *     `Component<Props>` prop bag.
 *   - the exposed methods (`ir.expose`) declared as PUBLIC class members
 *     (mirroring the Phase 21 21-06 public-element-method guarantee), and
 *   - a `declare global { interface HTMLElementTagNameMap { 'rozie-<kebab>':
 *     <Name> } }` entry so `document.querySelector('rozie-foo')` is typed.
 *
 * Output shape (canonical, Counter):
 *
 *   import type { LitElement } from 'lit';
 *
 *   export interface CounterProps {
 *     value?: number;
 *     defaultValue?: number;
 *     onValueChange?: (next: number) => void;
 *     step?: number;
 *   }
 *
 *   export default class Counter extends LitElement {
 *   }
 *
 *   declare global {
 *     interface HTMLElementTagNameMap {
 *       'rozie-counter': Counter;
 *     }
 *   }
 *
 * The kebab tag name is derived with the SAME `emitTagName` helper that
 * `@customElement` uses at runtime (emitDecorator.ts) so the map entry CANNOT
 * drift from the registered element (T-22-04-01).
 *
 * Slot idiom (Lit): Lit slots are projected as light-DOM children; the
 * slot-props surface is not part of the element-class consumer contract, so the
 * shared props body uses `'unknown'` as the slot-children token (import-free,
 * mirrors the conservative Vue choice in 22-03).
 *
 * NO do-not-edit header / source-hash is prepended here — the Wave-3 sidecar
 * WRITER owns that.
 *
 * @experimental — shape may change before v1.0
 */
import type { IRComponent } from '../../../../core/src/ir/types.js';
// `synthesizeHandleType` is not yet in the `@rozie/core` barrel (22-02-SUMMARY
// "Next Phase Readiness") — import it relatively as React/Vue's emitTypes.ts do.
import { synthesizeHandleType } from '../../../../core/src/codegen/synthesizeHandleType.js';
import { renderPropsInterface } from '@rozie/core';
// Reuse the SAME tag-deriving helper the runtime `@customElement` decorator
// uses so the HTMLElementTagNameMap key cannot drift from the registration.
import { emitTagName } from './emitDecorator.js';

/**
 * Options controlling Lit `.d.rozie.ts` emission.
 *
 * @experimental — shape may change before v1.0
 */
export interface EmitLitTypesOptions {
  /**
   * D-85 generic preservation: when set, emits
   * `export interface FooProps<T, ...>`.
   */
  genericParams?: string[];
}

/**
 * Extract the `name(...): ret;` / `name: (...) => ...;` member lines from a
 * `synthesizeHandleType` interface body, re-indented for an element-class body.
 *
 * `synthesizeHandleType` returns `interface <Name> {\n  member;\n  ...\n}` — we
 * want the inner member lines only, declared as PUBLIC class members (no
 * `private`/`protected`/`#`). The members are already access-modifier-free, so
 * splicing the interface-body lines verbatim into the class body yields public
 * members.
 */
function exposeMemberLines(handleInterface: string): string[] {
  const lines = handleInterface.split('\n');
  // Drop the opening `interface X {` line and the closing `}` line; keep the
  // already-2-space-indented member lines verbatim (public by default).
  return lines.slice(1, -1).filter((l) => l.trim().length > 0);
}

/**
 * Build a Lit `.d.rozie.ts` source string from an IRComponent.
 *
 * @public — consumed by the Wave-3 unplugin sidecar emit + CLI fallback.
 */
export function emitLitTypes(
  ir: IRComponent,
  opts: EmitLitTypesOptions = {},
): string {
  const exposed = (ir.expose ?? []).length > 0;
  const handleInterface = exposed
    ? synthesizeHandleType(ir, `${ir.name}Handle`)
    : null;

  const lines: string[] = [];
  // Type-only LitElement import — the element class extends it in the .d.ts.
  lines.push(`import type { LitElement } from 'lit';`);
  lines.push('');

  lines.push(
    renderPropsInterface(ir, {
      ...(opts.genericParams ? { genericParams: opts.genericParams } : {}),
      slotChildrenType: 'unknown',
    }),
  );
  lines.push('');

  // Lit default-export idiom: the element class. Exposed methods become PUBLIC
  // class members (Phase 21 21-06 public-element-method guarantee).
  lines.push(`export default class ${ir.name} extends LitElement {`);
  if (exposed && handleInterface) {
    for (const member of exposeMemberLines(handleInterface)) {
      lines.push(member);
    }
  }
  lines.push(`}`);
  lines.push('');

  // The novel Lit value-add: typed `document.querySelector('rozie-<kebab>')`.
  // The tag is derived with the SAME helper the runtime @customElement uses.
  const tag = emitTagName(ir.name);
  lines.push(`declare global {`);
  lines.push(`  interface HTMLElementTagNameMap {`);
  lines.push(`    '${tag}': ${ir.name};`);
  lines.push(`  }`);
  lines.push(`}`);
  lines.push('');
  return lines.join('\n');
}

// packages/targets/solid/src/emit/emitTypes.ts
/**
 * emitTypes (Solid) — Phase 22 Plan 22-03 (typed `.rozie` imports).
 *
 * Emits a sibling Solid `.d.rozie.ts` from an `IRComponent`. Mirrors React's
 * `emitTypes.ts` structure but:
 *   - consumes the Plan-02 core-shared `renderPropsInterface` for the
 *     framework-AGNOSTIC props-interface body (single source of truth — see the
 *     LOCKED CONTRACT in 22-02-SUMMARY.md),
 *   - swaps ONLY the framework default-export idiom to Solid's inline
 *     `import('solid-js').Component<<Name>Props>` form (PATTERNS Pattern 2
 *     table).
 *
 * Output shape (canonical):
 *
 *   export interface CounterProps {
 *     value?: number;
 *     defaultValue?: number;
 *     onValueChange?: (next: number) => void;
 *     step?: number;
 *   }
 *   declare const Counter: import('solid-js').Component<CounterProps>;
 *   export default Counter;
 *
 * Handle interface (Phase 21 $expose, REQ-2): when `ir.expose` is non-empty the
 * `<Name>Handle` interface is synthesized via the core-shared
 * `synthesizeHandleType` and exported alongside the default export. When empty,
 * NO handle interface is emitted. (Solid already consumes `synthesizeHandleType`
 * for its inline `ref?: (h: <Name>Handle) => void` prop — see the helper's own
 * docstring.)
 *
 * Slot idiom decision (Solid): Solid slot props are children-returning thunks
 * whose return type is `JSX.Element`. The slot-children token is `'JSX.Element'`
 * (the example token in the LOCKED CONTRACT). The inline `import('solid-js')`
 * default-export form keeps the sidecar header import-free; `JSX` resolves from
 * the consumer's Solid JSX namespace (ambient) at typecheck time.
 *
 * NO do-not-edit header / source-hash is prepended here — the Wave-3 sidecar
 * WRITER owns that.
 *
 * @experimental — shape may change before v1.0
 */
import type { IRComponent } from '@rozie/core';
import { renderPropsInterface } from '@rozie/core';
import { emitSlotDecl } from './emitSlotDecl.js';
import { buildSlotsRecordType } from './emitPropsInterface.js';
// `synthesizeHandleType` is not yet in the `@rozie/core` barrel — import it
// relatively as React's emitTypes.ts does.
import { synthesizeHandleType } from '../../../../core/src/codegen/synthesizeHandleType.js';

/**
 * Options controlling Solid `.d.rozie.ts` emission.
 *
 * @experimental — shape may change before v1.0
 */
export interface EmitSolidTypesOptions {
  /**
   * D-85 generic preservation: when set, emits
   * `export interface FooProps<T, ...>` and the inline
   * `import('solid-js').Component<FooProps<T, ...>>` default export.
   */
  genericParams?: string[];
}

/**
 * Build a Solid `.d.rozie.ts` source string from an IRComponent.
 *
 * @public — consumed by the Wave-3 unplugin sidecar emit + CLI fallback.
 */
export function emitSolidTypes(ir: IRComponent, opts: EmitSolidTypesOptions = {}): string {
  const exposed = (ir.expose ?? []).length > 0;
  const handleInterface = exposed ? synthesizeHandleType(ir, `${ir.name}Handle`) : null;

  const generics =
    opts.genericParams && opts.genericParams.length > 0 ? `<${opts.genericParams.join(', ')}>` : '';

  const lines: string[] = [];

  // Slot surface generated by the SAME function the compiled module uses
  // (emitSlotDecl), so the sidecar can never drift from the module.
  const slotDecl = emitSlotDecl(ir);
  // `JSX.Element` (slot fields) must resolve — an unresolved `JSX` silently
  // degrades every slot prop to `any` in a consumer with skipLibCheck.
  if (ir.slots.length > 0) {
    lines.push(`import type { JSX } from 'solid-js';`);
    lines.push('');
  }
  for (const iface of slotDecl.ctxInterfaces) lines.push(iface);
  if (slotDecl.ctxInterfaces.length > 0) lines.push('');

  lines.push(
    renderPropsInterface(ir, {
      ...(opts.genericParams ? { genericParams: opts.genericParams } : {}),
      slotChildrenType: 'JSX.Element',
      slotSurface: {
        fields: slotDecl.fields,
        ...(ir.slots.length > 0 ? { recordLine: `  slots?: ${buildSlotsRecordType(ir.slots)};` } : {}),
      },
      target: 'solid',
      // Typed public surface phase 3 — mirror the inline interface's
      // `extends Omit<ComponentProps<tag>, …>` in the public sidecar.
      htmlAttrs: 'solid',
      includeTypesBlock: true,
    }),
  );
  lines.push('');

  if (exposed && handleInterface) {
    lines.push(`export ${handleInterface}`);
    lines.push('');
  }

  lines.push(`declare const ${ir.name}: import('solid-js').Component<${ir.name}Props${generics}>;`);
  lines.push(`export default ${ir.name};`);
  lines.push('');
  return lines.join('\n');
}
