// packages/targets/solid/src/emit/emitTypes.ts
/**
 * emitTypes (Solid) — Phase 22 Plan 22-03 (typed `.rozie` imports).
 *
 * Emits a sibling Solid `.d.rozie.ts` from an `IRComponent`. Mirrors React's
 * `emitTypes.ts` structure but:
 *   - consumes the Plan-02 core-shared `renderPropsInterface` for the
 *     framework-AGNOSTIC props-interface body (single source of truth — see the
 *     LOCKED CONTRACT in 22-02-SUMMARY.md),
 *   - swaps ONLY the framework default-export idiom to Solid's inline
 *     `import('solid-js').Component<<Name>Props>` form (PATTERNS Pattern 2
 *     table).
 *
 * Output shape (canonical):
 *
 *   export interface CounterProps {
 *     value?: number;
 *     defaultValue?: number;
 *     onValueChange?: (next: number) => void;
 *     step?: number;
 *   }
 *   declare const Counter: import('solid-js').Component<CounterProps>;
 *   export default Counter;
 *
 * Handle interface (Phase 21 $expose, REQ-2): when `ir.expose` is non-empty the
 * `<Name>Handle` interface is synthesized via the core-shared
 * `synthesizeHandleType` and exported alongside the default export. When empty,
 * NO handle interface is emitted. (Solid already consumes `synthesizeHandleType`
 * for its inline `ref?: (h: <Name>Handle) => void` prop — see the helper's own
 * docstring.)
 *
 * Slot idiom decision (Solid): Solid slot props are children-returning thunks
 * whose return type is `JSX.Element`. The slot-children token is `'JSX.Element'`
 * (the example token in the LOCKED CONTRACT). The inline `import('solid-js')`
 * default-export form keeps the sidecar header import-free; `JSX` resolves from
 * the consumer's Solid JSX namespace (ambient) at typecheck time.
 *
 * NO do-not-edit header / source-hash is prepended here — the Wave-3 sidecar
 * WRITER owns that.
 *
 * @experimental — shape may change before v1.0
 */
import type { IRComponent } from '@rozie/core';
import { renderPropsInterface } from '@rozie/core';
import { emitSlotDecl } from './emitSlotDecl.js';
import { buildSlotsRecordType } from './emitPropsInterface.js';
// `synthesizeHandleType` is not yet in the `@rozie/core` barrel — import it
// relatively as React's emitTypes.ts does.
import { synthesizeHandleType } from '../../../../core/src/codegen/synthesizeHandleType.js';

/**
 * Options controlling Solid `.d.rozie.ts` emission.
 *
 * @experimental — shape may change before v1.0
 */
export interface EmitSolidTypesOptions {
  /**
   * D-85 generic preservation: when set, emits
   * `export interface FooProps<T, ...>` and the inline
   * `import('solid-js').Component<FooProps<T, ...>>` default export.
   */
  genericParams?: string[];
}

/**
 * Build a Solid `.d.rozie.ts` source string from an IRComponent.
 *
 * @public — consumed by the Wave-3 unplugin sidecar emit + CLI fallback.
 */
export function emitSolidTypes(ir: IRComponent, opts: EmitSolidTypesOptions = {}): string {
  const exposed = (ir.expose ?? []).length > 0;
  const handleInterface = exposed ? synthesizeHandleType(ir, `${ir.name}Handle`) : null;

  const generics =
    opts.genericParams && opts.genericParams.length > 0 ? `<${opts.genericParams.join(', ')}>` : '';

  const lines: string[] = [];

  // Slot surface generated by the SAME function the compiled module uses
  // (emitSlotDecl), so the sidecar can never drift from the module.
  const slotDecl = emitSlotDecl(ir);
  // `JSX.Element` (slot fields) must resolve — an unresolved `JSX` silently
  // degrades every slot prop to `any` in a consumer with skipLibCheck.
  if (ir.slots.length > 0) {
    lines.push(`import type { JSX } from 'solid-js';`);
    lines.push('');
  }
  for (const iface of slotDecl.ctxInterfaces) lines.push(iface);
  if (slotDecl.ctxInterfaces.length > 0) lines.push('');

  lines.push(
    renderPropsInterface(ir, {
      ...(opts.genericParams ? { genericParams: opts.genericParams } : {}),
      slotChildrenType: 'JSX.Element',
      slotSurface: {
        fields: slotDecl.fields,
        ...(ir.slots.length > 0 ? { recordLine: `  slots?: ${buildSlotsRecordType(ir.slots)};` } : {}),
      },
      target: 'solid',
      // Typed public surface phase 3 — mirror the inline interface's
      // `extends Omit<ComponentProps<tag>, …>` in the public sidecar.
      htmlAttrs: 'solid',
      includeTypesBlock: true,
    }),
  );
  lines.push('');

  if (exposed && handleInterface) {
    lines.push(`export ${handleInterface}`);
    lines.push('');
  }

  lines.push(`declare const ${ir.name}: import('solid-js').Component<${ir.name}Props${generics}>;`);
  lines.push(`export default ${ir.name};`);
  lines.push('');
  return lines.join('\n');
}

// packages/targets/react/src/emit/emitTypes.ts
/**
 * emitTypes — Phase 6 Plan 06-02 Task 1.
 *
 * Emits a sibling React `.d.ts` from an `IRComponent` per CONTEXT D-84
 * (hand-rolled string builder; NO `tsc --emitDeclarationOnly` round-trip).
 *
 * Output shape (canonical):
 *
 *   import type { ReactNode } from 'react';
 *   export interface CounterProps {
 *     value?: number;
 *     defaultValue?: number;
 *     onValueChange?: (next: number) => void;
 *     step?: number;
 *     renderTrigger?: (params: { open: boolean; toggle: () => void }) => ReactNode;
 *     children?: ReactNode;
 *   }
 *   declare function Counter(props: CounterProps): JSX.Element;
 *   export default Counter;
 *
 * Decisions implemented:
 *   - D-84 model:true triplet — `value? / defaultValue? / onValueChange?` named
 *     after the prop's actual identifier (not always `value`).
 *   - D-85 React full generic preservation — when `opts.genericParams` is set,
 *     the interface AND the function signature both carry the type-parameter list.
 *   - D-86 best-effort param-type inference — slot-param `valueExpression` is
 *     resolved against `ir.props` (member-expressions like `$props.open` and
 *     bare identifiers) with `'unknown'` as the genuine fallback for anything
 *     unresolved. (Quick 260802-v1v seam 7 — an unresolved bare identifier
 *     PREVIOUSLY emitted a best-effort `() => void` callable guess; removed
 *     because it could not distinguish a real script-defined callback
 *     (Dropdown's `toggle`) from an `r-for` loop variable — both are
 *     unresolved bare identifiers at this call site, and the guess silently
 *     lied about the loop-var shape. Both now fall to `unknown`.)
 *
 * Per Pitfall 2 (Oxc isolated-decl): every exported function carries an
 * explicit return-type annotation so tsdown's isolated-decl typegen succeeds
 * without a full type-check.
 *
 * @experimental — shape may change before v1.0
 */
import type { IRComponent } from '../../../../core/src/ir/types.js';
import { synthesizeHandleType } from '../../../../core/src/codegen/synthesizeHandleType.js';
// Phase 22 Plan 22-02 — the framework-agnostic props-interface body is now
// rendered by a single core-shared function so the five Wave-2 per-target
// renderers cannot drift from the React prop→TS-type mapping. React passes its
// own slot-children token (`ReactNode`); the per-target default-export
// declaration below stays React-specific.
import { renderPropsInterface } from '../../../../core/src/codegen/renderPropsInterface.js';

/**
 * Options controlling .d.ts emission.
 *
 * @experimental — shape may change before v1.0
 */
export interface EmitReactTypesOptions {
  /**
   * D-85 React full: when set, emits `interface FooProps<T, ...>` and
   * `declare function Foo<T, ...>(props: FooProps<T, ...>): JSX.Element;`.
   *
   * Validation note (T-06-02-03 in threat register): each entry MUST be a
   * valid TypeScript identifier. The Phase 1 parser does NOT yet accept
   * user-authored generic syntax, so this option is currently set ONLY by
   * tests and direct callers — no consumer-controlled path exists in v1.
   */
  genericParams?: string[];
  /**
   * Phase 06.2 P3 D-121: RESERVED — accepted-but-ignored in v1.0. Reserved
   * for future cross-rozie type-graph features (forward-referencing prop /
   * event types from composed `.rozie` files, e.g. emitting
   * `import type { CardHeaderProps } from './CardHeader';` in `Card.d.ts`
   * when CardHeader is in `<components>`). Pass an empty `Map` to be
   * explicit; v1.0 simply discards the value.
   *
   * @experimental — semantics subject to change pre-1.0; see
   * `.planning/notes/phase-6-composition-foresight.md`.
   */
  linkedComponents?: Map<string, IRComponent>;
}

/**
 * Build an `.d.ts` source string from an IRComponent.
 *
 * @public — consumed by `compile()` for the React target and by
 * Plan 06-05's bootstrap script for consumer-ts fixture refresh.
 */
export function emitReactTypes(
  ir: IRComponent,
  opts: EmitReactTypesOptions = {},
): string {
  // Phase 06.2 P3 D-121: linkedComponents is RESERVED in v1.0 — accepted
  // but unused. The body below stays unchanged; opts.linkedComponents will
  // drive future cross-rozie type imports (e.g. `import type { ChildProps }
  // from './Child';`) once the type-graph resolver lands. void-ing the field
  // suppresses unused-locals warnings without consuming it.
  void opts.linkedComponents;

  // Phase 21 ($expose, REQ-10, D-03) — synthesize the `<Name>Handle` interface
  // and switch the component declaration to a forwardRef-typed `declare const`
  // ONLY when ir.expose is non-empty. When empty, the import line + the
  // `declare function` form below stay BYTE-FOR-BYTE unchanged.
  // Defensive `?? []` guards pre-Phase-21 hand-rolled IRs (legacy emitTypes
  // tests construct minimal IRs without the `expose` field; real lowered IRs
  // always carry `expose: []`). Mirrors the `ir.components ?? []` guard in
  // emitReact.ts.
  const exposed = (ir.expose ?? []).length > 0;
  const handleInterface = exposed
    ? synthesizeHandleType(ir, `${ir.name}Handle`)
    : null;

  const lines: string[] = [];
  lines.push(`import type { ReactNode } from 'react';`);
  if (exposed) {
    // `ForwardRefExoticComponent` / `RefAttributes` are referenced via the
    // `React.` namespace in the declaration below (matching the SPEC Req 10
    // shape); import them as named types AND bring the `React` namespace into
    // scope so both `React.ForwardRefExoticComponent` and the named forms
    // resolve regardless of how downstream tooling reads the declaration.
    lines.push(`import type { ForwardRefExoticComponent, RefAttributes } from 'react';`);
    lines.push(`import type * as React from 'react';`);
  }
  lines.push('');

  const generics =
    opts.genericParams && opts.genericParams.length > 0
      ? `<${opts.genericParams.join(', ')}>`
      : '';

  // Phase 22 Plan 22-02 — the entire `export interface ${ir.name}Props { … }`
  // body (model-triplet, required/optional gating, ir.emits→on<Event>, slot
  // params, the slots?: mirror field) is now rendered by the core-shared
  // `renderPropsInterface`. React passes its own slot-children token
  // (`ReactNode`). The output is BYTE-IDENTICAL to the prior inline loop — the
  // existing emitTypes snapshot suite is the byte-identity guard (NO rebless).
  lines.push(
    renderPropsInterface(ir, {
      // Spread the optional generics only when present — the core option type
      // is `exactOptionalPropertyTypes`-clean (an explicit `undefined` is
      // rejected; omit the key instead).
      ...(opts.genericParams ? { genericParams: opts.genericParams } : {}),
      slotChildrenType: 'ReactNode',
    }),
  );
  lines.push('');

  // Phase 21 ($expose, REQ-10) — the exported handle interface + the
  // forwardRef-typed component declaration. When NOT exposed, emit the
  // unchanged `declare function` form (D-03 byte-identity).
  if (exposed && handleInterface) {
    // synthesizeHandleType returns the interface WITHOUT `export`; prepend it
    // for the `.d.ts` surface.
    lines.push(`export ${handleInterface}`);
    lines.push('');
    lines.push(
      `declare const ${ir.name}: React.ForwardRefExoticComponent<${ir.name}Props${generics} & React.RefAttributes<${ir.name}Handle>>;`,
    );
  } else {
    lines.push(
      `declare function ${ir.name}${generics}(props: ${ir.name}Props${generics}): JSX.Element;`,
    );
  }
  lines.push(`export default ${ir.name};`);
  lines.push('');
  return lines.join('\n');
}
