// packages/targets/angular/src/emit/shell.ts
/**
 * shell.ts — Phase 5 Plan 05-04a Task 3 (default-export added in Plan 05-04b);
 * Phase 06.1 Plan 01 Task 4 rearchitecture.
 *
 * Composes the Angular standalone-component .ts file by anchoring
 * `magic-string`'s MagicString at the original `.rozie` source bytes and
 * using `ms.overwrite(...)` over the `<rozie>` envelope's byte range with
 * the entire Angular module body (Phase 06.1 P1, DX-04). Per-expression
 * accuracy inside the class body lands in P2 via @babel/generator's child
 * sourcemap chained through composeMaps().
 *
 * Block order:
 *
 *   1. Imports (`@angular/core`, `@angular/common`, `@angular/forms`)
 *   2. Per-slot context interfaces (rendered above the class)
 *   3. @Component({...}) decorator
 *   4. export class Name { ... }
 *   5. export default Name; (Plan 05-04b — consumer-side default-import compat).
 *
 * Returning a `BuildShellResult` (not a plain MagicString) lets `emitAngular`
 * later call `composeSourceMap(ms, ...)` to thread the source map.
 *
 * @experimental — shape may change before v1.0
 */
import MagicString from 'magic-string';
import type { EncodedSourceMap } from '@ampproject/remapping';
import type { BlockMap } from '../../../../core/src/ast/types.js';

export interface ShellParts {
  /** `import { ... } from '@angular/core';` (and common/forms lines if needed). */
  importLines: string;
  /** Standalone interface declarations for slot contexts (rendered above class). */
  interfaceDecls: string[];
  /** Full @Component({...}) decorator block. */
  decorator: string;
  /** Component class name (e.g., `Counter`). */
  componentName: string;
  /** Class body (lines inside `class X { ... }`, without surrounding braces). */
  classBody: string;
  /**
   * Phase 06.1 Plan 01: original `.rozie` source text — anchors the MagicString.
   */
  rozieSource: string;
  /**
   * Phase 06.1 Plan 01: block byte offsets from splitBlocks() — used to
   * anchor the Angular module's overwrite range at the `<rozie>` envelope.
   */
  blockOffsets: BlockMap;
  /**
   * Phase 06.1 P2 (D-101): per-expression child sourcemap from emitScript;
   * pass-through to BuildShellResult for composeMaps() consumption.
   */
  scriptMap?: EncodedSourceMap | null;
  /**
   * Phase 06.1 P2: number of lines in the class body BEFORE user-authored
   * constructor-expression statements (from emitScript.preambleSectionLines).
   * Used to compute userCodeLineOffset in BuildShellResult.
   */
  preambleSectionLines?: number;
  /**
   * Phase 06.2 P2 (D-118): synthesized component-import lines for the
   * top-of-file imports section. Each line is `import { LocalName } from '{rewrittenPath}';\n`
   * (NAMED import — Angular standalone components export the class by name).
   *
   * Self-references are NOT included here — emitAngular filters out
   * `localName === ir.name` and the class is referenced via
   * `forwardRef(() => Self)` inside `@Component({ imports: [...] })`
   * (the class is in scope of its own decorator).
   *
   * Empty/undefined when no `<components>` block was authored (or every
   * entry was the self-entry that got filtered).
   */
  componentImportsBlock?: string;
  /**
   * Spike 001 B1 — user-authored `<script>` `ImportDeclaration` statements
   * rendered as a string by emitScript. Placed AFTER target/component imports,
   * BEFORE the slot ctx interface declarations. Empty when no user imports.
   */
  userImports?: string;
}

/**
 * Phase 06.1 Plan 01 D-101: buildShell return shape carries both the
 * byte-anchored MagicString AND the script-body offset within the rendered
 * shell so P2's composeMaps() can chain @babel/generator's per-expression
 * child map at the correct output position.
 */
export interface BuildShellResult {
  /** MagicString anchored to rozieSource with whole-module overwrite + outer-region remove. */
  ms: MagicString;
  /** Byte offset within ms.toString() where the class body opens (after `export class Name {\n`). */
  scriptOutputOffset: number;
  /**
   * Phase 06.1 P2 (D-101): pass-through of emitScript's per-expression child
   * map. composeMaps() chains this into the shell map at scriptOutputOffset.
   * null when no child map produced (D-102 fallback).
   */
  scriptMap: EncodedSourceMap | null;
  /**
   * Phase 06.1 P2: 0-indexed line offset of the user-authored constructor-
   * expression statements within the full .ts output. Computed as the number
   * of newlines before the class body in the shell + preambleSectionLines
   * from emitScript. composeMaps uses this to shift the script map so it
   * references actual .ts output line numbers.
   */
  userCodeLineOffset: number;
}

export function buildShell(parts: ShellParts): BuildShellResult {
  const blocks = parts.blockOffsets;

  // Back-compat fallback: empty rozieSource or missing envelope offsets.
  if (parts.rozieSource.length === 0 || !blocks.rozie) {
    return buildShellLegacy(parts);
  }

  const ms = new MagicString(parts.rozieSource);

  // Assemble the entire Angular standalone-component module as a single string.
  // Same approach as React: anchor at the <rozie> envelope's byte range;
  // remove everything outside.
  const moduleParts: string[] = [];

  if (parts.importLines.length > 0) {
    moduleParts.push(parts.importLines);
    moduleParts.push('\n');
  }

  // Phase 06.2 P2 (D-118): user-component named imports.
  if (parts.componentImportsBlock && parts.componentImportsBlock.length > 0) {
    moduleParts.push(parts.componentImportsBlock);
    moduleParts.push('\n');
  }

  // Spike 001 B1 — user-authored `<script>` imports.
  if (parts.userImports && parts.userImports.length > 0) {
    moduleParts.push(parts.userImports);
    moduleParts.push('\n');
  }

  if (parts.interfaceDecls.length > 0) {
    for (const decl of parts.interfaceDecls) {
      moduleParts.push(decl);
      moduleParts.push('\n\n');
    }
  }

  moduleParts.push(parts.decorator);
  moduleParts.push('\n');
  moduleParts.push(`export class ${parts.componentName} {\n`);

  // Record class-body offset BEFORE class body content (P2 will use this).
  const preClassBodyLength = moduleParts.join('').length;

  // Indent each line of class body by 2 spaces.
  const indented = parts.classBody
    .split('\n')
    .map((line) => (line.length > 0 ? '  ' + line : line))
    .join('\n');
  moduleParts.push(indented);
  moduleParts.push('\n}\n');

  // Plan 05-04b: emit `export default ClassName;` so consumer-side
  // `import Foo from './Foo.rozie'` works (mirrors how Vue/Svelte/React
  // synthesise default exports for their respective virtual ids).
  moduleParts.push(`\nexport default ${parts.componentName};\n`);

  const moduleSource = moduleParts.join('');

  // Compute userCodeLineOffset: number of newlines in the output before the
  // user-authored constructor-expression statements. This is:
  //   - newlines in the shell output up to (and including) the class opening line
  //   - + preambleSectionLines from emitScript (field lines + blank + ctor header)
  // The text up to preClassBodyLength includes everything from imports through
  // `export class Name {\n`; counting its newlines gives lines before class body.
  const preClassBodyText = moduleSource.slice(0, preClassBodyLength);
  const linesBeforeClassBody = (preClassBodyText.match(/\n/g) ?? []).length;
  const preambleSectionLines = parts.preambleSectionLines ?? 0;
  const userCodeLineOffset = linesBeforeClassBody + preambleSectionLines;

  // Anchor the entire Angular module at the `<rozie>` envelope's byte range.
  const anchorStart = blocks.rozie.loc.start;
  const anchorEnd = blocks.rozie.loc.end;
  ms.overwrite(anchorStart, anchorEnd, moduleSource);

  // Remove pre-envelope and post-envelope characters (e.g. leading whitespace,
  // trailing newlines, HTML comments outside the envelope).
  if (anchorStart > 0) ms.remove(0, anchorStart);
  if (anchorEnd < parts.rozieSource.length)
    ms.remove(anchorEnd, parts.rozieSource.length);

  return {
    ms,
    scriptOutputOffset: preClassBodyLength,
    scriptMap: parts.scriptMap ?? null,
    userCodeLineOffset,
  };
}

/**
 * Legacy fallback path — empty rozieSource or missing envelope.
 * Constructs the Angular module from scratch on an empty MagicString,
 * preserving pre-Phase-06.1 behavior so old callers (tests that don't
 * thread opts.source through) keep working.
 */
function buildShellLegacy(parts: ShellParts): BuildShellResult {
  const ms = new MagicString('');

  if (parts.importLines.length > 0) {
    ms.append(parts.importLines);
    ms.append('\n');
  }

  // Phase 06.2 P2 (D-118): user-component named imports.
  if (parts.componentImportsBlock && parts.componentImportsBlock.length > 0) {
    ms.append(parts.componentImportsBlock);
    ms.append('\n');
  }

  // Spike 001 B1 — user-authored `<script>` imports.
  if (parts.userImports && parts.userImports.length > 0) {
    ms.append(parts.userImports);
    ms.append('\n');
  }

  if (parts.interfaceDecls.length > 0) {
    for (const decl of parts.interfaceDecls) {
      ms.append(decl);
      ms.append('\n\n');
    }
  }

  ms.append(parts.decorator);
  ms.append('\n');
  ms.append(`export class ${parts.componentName} {\n`);

  const indented = parts.classBody
    .split('\n')
    .map((line) => (line.length > 0 ? '  ' + line : line))
    .join('\n');
  ms.append(indented);
  ms.append('\n}\n');

  ms.append(`\nexport default ${parts.componentName};\n`);

  return { ms, scriptOutputOffset: 0, scriptMap: parts.scriptMap ?? null, userCodeLineOffset: 0 };
}

// packages/targets/lit/src/emit/shell.ts
/**
 * shell.ts — assembles the Lit `.ts` module from emitted parts.
 *
 * Block order (D-LIT carry-forward):
 *
 *   1. Import lines (lit, lit/decorators.js, @lit-labs/preact-signals, @rozie/runtime-lit)
 *   2. Component side-effect imports (`import './Foo.rozie';` per D-LIT — module
 *      load registers the custom element via customElements.define)
 *   3. Per-slot context interfaces (e.g., `interface RozieSlotXCtx { ... }`)
 *   4. @customElement('rozie-x') decorator
 *   5. `export default class Name extends SignalWatcher(LitElement) { ... }`
 *   6. Optional `injectGlobalStyles('rozie-x-global', ...)` call AFTER the class
 *      (D-LIT-15 — non-:root rules go INTO `static styles = css\`...\``).
 *
 * @experimental — shape may change before v1.0
 */
import MagicString from 'magic-string';
import type { EncodedSourceMap } from '@ampproject/remapping';
import type { BlockMap } from '../../../../core/src/ast/types.js';

export interface LitShellParts {
  /** Import lines for `lit`, `lit/decorators.js`, `@lit-labs/preact-signals`, `@rozie/runtime-lit`. */
  importLines: string;
  /**
   * Side-effect composition imports — for cross-rozie `<components>` entries
   * we emit `import './Foo.rozie';` (D-LIT — module load registers the custom
   * element via customElements.define). No symbol binding.
   */
  componentImportsBlock?: string | undefined;
  /**
   * Spike 001 B1 — user-authored `<script>` `ImportDeclaration` statements
   * rendered as a string by emitScript. Placed AFTER target/component imports,
   * BEFORE the blank line that separates imports from interface decls.
   * Empty when no user imports.
   */
  userImports?: string | undefined;
  /** Standalone `interface XCtx { ... }` declarations from emitSlotDecl. */
  interfaceDecls: string[];
  /** `@customElement('rozie-counter')` decorator line. */
  customElementDecorator: string;
  /** Component class name (e.g. `Counter`). */
  componentName: string;
  /** `SignalWatcher(LitElement)` — D-LIT-08 reactive base. */
  baseClassExpression: string;
  /** Pre-assembled class body — fields, decorators, methods, render(). */
  classBody: string;
  /** Optional `injectGlobalStyles('rozie-counter-global', ...);` call emitted AFTER the class. */
  globalStyleIife?: string | undefined;
  /** Original .rozie source — used by sourcemap/compose (not yet wired in P2). */
  rozieSource: string;
  /** Block byte offsets from splitBlocks. */
  blockOffsets: BlockMap;
  /** Per-expression child map from emitScript (P2 unused). */
  scriptMap?: EncodedSourceMap | null | undefined;
  /** 0-indexed line offset of user-authored script statements in shell output. */
  preambleSectionLines?: number | undefined;
}

export interface BuildShellResult {
  ms: MagicString;
  scriptOutputOffset: number;
  scriptMap: EncodedSourceMap | null;
}

export function buildShell(parts: LitShellParts): BuildShellResult {
  const moduleParts: string[] = [];

  if (parts.importLines.length > 0) {
    moduleParts.push(parts.importLines);
    if (!parts.importLines.endsWith('\n')) moduleParts.push('\n');
  }

  if (parts.componentImportsBlock && parts.componentImportsBlock.length > 0) {
    moduleParts.push(parts.componentImportsBlock);
    if (!parts.componentImportsBlock.endsWith('\n')) moduleParts.push('\n');
  }

  // Spike 001 B1 — user-authored `<script>` imports, AFTER target/component
  // imports, BEFORE the blank-line separator.
  if (parts.userImports && parts.userImports.length > 0) {
    moduleParts.push(parts.userImports);
    if (!parts.userImports.endsWith('\n')) moduleParts.push('\n');
  }

  // Blank line after imports.
  if (moduleParts.length > 0) moduleParts.push('\n');

  for (const decl of parts.interfaceDecls) {
    moduleParts.push(decl);
    moduleParts.push('\n\n');
  }

  moduleParts.push(parts.customElementDecorator);
  moduleParts.push('\n');
  moduleParts.push(
    `export default class ${parts.componentName} extends ${parts.baseClassExpression} {\n`,
  );

  // Indent class body by 2 spaces — but emitters already indent their own
  // sub-content; here we only wrap with a 2-space outer prefix for top-level
  // class statements that didn't include it.
  // The composeClassBody output already aligns lines to a 2-space class-body
  // indent. We pass it through verbatim.
  moduleParts.push(parts.classBody);
  if (!parts.classBody.endsWith('\n')) moduleParts.push('\n');
  moduleParts.push('}\n');

  if (parts.globalStyleIife && parts.globalStyleIife.trim().length > 0) {
    moduleParts.push('\n');
    moduleParts.push(parts.globalStyleIife);
    if (!parts.globalStyleIife.endsWith('\n')) moduleParts.push('\n');
  }

  const moduleSource = moduleParts.join('');
  const ms = new MagicString(moduleSource);
  return { ms, scriptOutputOffset: 0, scriptMap: parts.scriptMap ?? null };
}
